(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[251,505,148,62],[322,394,161,109],[322,202,111,190],[0,482,143,92],[322,0,140,200],[0,0,320,480],[145,482,104,93]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.interstitialapples = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.interstitialcinnamonbuns = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.interstitialholidaymainsbrusselsprouts = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.interstitialholidaymainscrannberries = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.interstitialholidaymainspotatoes = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.interstitialholidaymainstable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.interstitialstuffing = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.youtakethecredit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgIAJQgFgEAAgFQAAgFAFgEQADgDAFAAQAFAAAFADQADAEAAAFQAAAFgDAEQgFAFgFAAQgFAAgDgFg");
	this.shape.setTransform(114.5,9.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgCBFIgGgBQgEgBAAgEIAAhmQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBgBQgBgBgFAAIgLAAIgKAAIgGAAQgEAAgBgDQgCgDAAgEIAAgEIABgFIACgDQAAgBABAAQAAAAAAAAQABgBABAAQAAAAABAAIBfAAQAEAAABADIACAGIAAAEIgBAFIgCAEQgBABAAAAQAAAAgBAAQAAABgBAAQgBAAAAAAIgcAAQgDAAgCABQgDACAAAEIABBkQAAAEgCABIgEACIgFABg");
	this.shape_1.setTransform(105.9,3.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AgEBHQgGAAgCgEIAAiFQAAgBABAAQAAgBABAAQAAAAABgBQAAAAABAAIAEgCIAFAAIAFAAQAFAAACAFIAACEQgBABAAAAQAAABgBAAQAAABAAAAQgBAAAAAAIgFACIgFAAg");
	this.shape_2.setTransform(97.1,3.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("Ag6BFIgFgBQgCgBAAgEIAAh9QAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBABAAQACgCADAAIAzAAIAOACIAOADQANAFAKAJQAKAJAGAMQADAHACAHQABAHAAAHQAAAQgGANIgHAMIgJAKIgLAIIgNAGQgNAEgOAAgAglgpQgDACAAADIAABLQAAACADACIAFACIAZAAQAJAAAJgDQAIgEAHgFQAHgGAEgJQAEgHAAgLQAAgJgEgJQgEgHgHgGQgHgHgIgCQgJgEgJAAIgZAAQgDAAgCADg");
	this.shape_3.setTransform(86.7,3.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AgvBFIgEgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAIAAh/QAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABAAIAEgCIBgAAQABAAAAAAQABABAAAAQABAAAAABQAAAAABAAIABAEIAAAFIAAAEIgBAFIgEAEIhHAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAABQgBAAAAABQgBAAAAABQAAAAAAAAQAAABAAAAIAAATQAAADABACQACABADABIAtAAQABAAABAAQAAAAABAAQAAAAAAABQAAAAABAAIABAFIABAFIAAAEQAAAFgGADIgtAAQgCAAgCACQgBAAAAABQgBABAAAAQAAABAAAAQAAABAAAAIAAAWQAAACABACQACACADAAIBGAAQAFACAAAGIAAAEIAAAFIgCAGQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_4.setTransform(72.2,3.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AAjBGIgEgBIgCgBIgCgCIgYgkIgDgFQgDgCgEAAIgRAAQgDAAgCADQgCABAAADIAAAiQAAABAAAAQAAABAAABQgBAAAAAAQgBABAAAAIgFACIgFAAIgFAAQgEAAgCgCQgCgBAAgFIAAh+QAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAQAAgBAAAAQABAAABAAQAAAAABAAIA6AAQAKAAAJADQAKADAGAGQAHAGADAJQAEAJAAALQAAALgEAIQgFAGgFAEIgKAIQgEADAAADIAAADIAGAHIAIAMIAHALQADAFAAACQAAAAAAABQAAABgBAAQAAAAAAABQAAAAgBABIgEADIgFACIgFAAgAgcgsQgDACAAAEIAAAfQAAAEADACQADABADAAIAcAAQAFAAAFgBQAFgBADgDQAEgDACgEQACgFAAgFQAAgMgIgGQgDgCgFgCQgFgBgFAAIgcAAIgGABg");
	this.shape_5.setTransform(58.3,3.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgFBHIgOgEIgNgHIgLgIIgJgLIgHgMQgGgNAAgQQAAgOAGgOIAHgMQAEgGAFgEQAKgKAOgGIAOgEQAGgBAHAAQAIAAAIACQAIABAIAEQAHADAHAFQAGAEAFAHIABADQAAAEgDACIgFAEIgEACQgDACgCAAQgDAAgDgDIgHgGQgEgEgHgDQgHgDgKAAQgIAAgJAEQgIAEgHAHQgGAGgEAJQgEAJAAAIQAAAKAEAJQAEAIAGAHQAHAGAIAEQAJAEAIAAQALAAAJgEQAKgEAHgIIAEgBIAFABIAFADIAFAEQAAABABAAQAAABAAABQABAAAAABQAAAAAAABIgBADIgMALIgNAIIgQAFQgHABgJAAQgHAAgGgBg");
	this.shape_6.setTransform(43.2,3.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AgvBFIgEgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAIAAh/QAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABAAIAEgCIBgAAQABAAAAAAQABABAAAAQABAAAAABQAAAAABAAIABAEIAAAFIAAAEIgBAFIgEAEIhHAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAABQgBAAAAABQgBAAAAABQAAAAAAAAQAAABAAAAIAAATQAAADABACQACABADABIAtAAQABAAABAAQAAAAABAAQAAAAAAABQAAAAABAAIABAFIABAFIAAAEQAAAFgGADIgtAAQgCAAgCACQgBAAAAABQgBABAAAAQAAABAAAAQAAABAAAAIAAAWQAAACABACQACACADAAIBGAAQAFACAAAGIAAAEIAAAFIgCAGQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_7.setTransform(24.1,3.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AAlBGQgDgBgCgCIAAgxQAAgDgDgDQgCgCgDAAIguAAQgDAAgDADQgCADAAADIAAAvQAAABAAAAQgBABAAAAQAAABgBAAQAAABgBAAIgFABIgFAAIgFAAIgFgBQAAAAgBgBQAAAAgBgBQAAAAgBgBQAAAAAAgBIAAiDIADgDIAFgCIAFAAIAEAAQAGAAADAFIAAAtIABAFQACACADAAIAwAAQADAAACgCQADgCAAgEIAAgsQACgEAEAAIAJgBIAGABQACABACADIAACDQgCAEgEABIgJAAg");
	this.shape_8.setTransform(9.3,3.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AgCBFIgGgBQgEgBAAgEIAAhmQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBgBQgBgBgFAAIgLAAIgKAAIgGAAQgEAAgBgDQgCgDAAgEIAAgEIABgFIACgDQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAIBfAAQAEAAABADIACAGIAAAEIgBAFIgCAEQgBABAAAAQgBAAAAAAQAAABgBAAQgBAAAAAAIgcAAQgDAAgCABQgDACAAAEIABBkQAAAEgCABIgEACIgFABg");
	this.shape_9.setTransform(-4.1,3.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AguBFIgFgBQAAgBgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAIAAh/QAAgBAAAAQAAgBAAAAQABgBAAAAQABAAAAAAIAEgCIBgAAQABAAAAAAQABABAAAAQABAAAAABQAAAAABAAIABAEIAAAFIAAAEIgBAFIgEAEIhHAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABgBABQAAAAAAABQgBAAAAABQAAAAAAAAQAAABAAAAIAAATQgBADACACQACABADABIAuAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAAAIACAFIAAAFIAAAEQAAAFgEADIgtAAQgDAAgDACQAAAAAAABQgBABAAAAQAAABAAAAQAAABAAAAIAAAWQgBACACACQACACADAAIBGAAQAEACABAGIAAAEIAAAFIgCAGQAAAAgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_10.setTransform(-21.6,3.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AAgBHQgEgBgBgCIgig0QgBgCgEgBIgFgCQgEAAgDACQgFACAAAEIAAArQAAADgCACIgEACIgGABIgFAAQgIAAABgHIAAiBIADgDIADgCIAFAAIAEAAQAHAAACAFIAAArQAAADAEACQACACADAAQADAAADgDIAmgvIADgBIADgBIAEABIAFADIAFAEQAAAAABABQAAAAAAAAQAAABAAAAQABABAAAAIgBADIgiAoIgCADIAAAEIAAADIABADIAsA8IABACIAAACQAAAAgBABQAAAAAAABQAAAAgBABQAAAAgBABIgEADIgGACIgEAAg");
	this.shape_11.setTransform(-35,3.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E46").s().p("AAyBGIgHgBQgEgBgBgEIgIgSIgCgDIgEgBIguAAIgCAAIgCACIgCABIgBABIgIASIgCADIgEACIgEABIgEAAIgEAAIgEgBIgEgCQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIA4iBQAAgBABAAQAAgBABAAQAAAAABgBQAAAAABAAIAEgBIAGAAQAEABABADIA2CBIAAABQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAABIgEABIgFAAgAgBgVIgBACIgCADIgDAHIgDAIIgDAHIgDAGIgBADIABADIADABIAbAAIADgBIABgDIgCgGIgFgKIgEgMIgDgHQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAgBgBAAg");
	this.shape_12.setTransform(-49.1,3.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E46").s().p("AgCBFIgGgBQgEgBAAgEIAAhmQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBgBQgBgBgFAAIgLAAIgKAAIgGAAQgEAAgBgDQgCgDAAgEIAAgEIABgFIACgDQAAgBABAAQAAAAAAAAQABgBABAAQAAAAABAAIBfAAQAEAAABADIACAGIAAAEIgBAFIgCAEQgBABAAAAQAAAAgBAAQAAABgBAAQgBAAAAAAIgcAAQgDAAgCABQgDACAAAEIABBkQAAAEgCABIgEACIgFABg");
	this.shape_13.setTransform(-61.5,3.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E46").s().p("AgXBDQgLgEgIgIQgIgIgFgKQgDgGgBgGIgBgMIAAgmIAAgmQAAAAAAgBQAAgBABAAQAAgBAAAAQAAAAABgBIAEgCIAGgBIAEAAIAGACQADABAAADIAABHQAAAIADAIQACAHAFAFQAEAGAHADQAHAEAHAAQAJAAAGgEQAHgDAFgFQAEgGADgHQACgIAAgIIAAhGQAAgEADgCQADgBADAAIAFgBIAGABIAEACQABACAAADIAABMIgBAMIgEAMQgEAKgJAIQgIAIgLAEQgLAFgNAAQgMAAgLgFg");
	this.shape_14.setTransform(-80.8,3.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E46").s().p("AgOBGIgOgDIgNgHIgKgJQgLgKgGgNQgCgGgCgIIgBgOIABgOQACgHACgHQAGgNALgJIAKgJQAGgEAHgDQAGgCAIgBQAHgCAHAAQAIAAAHACQAHABAHACQAOAGAJAKQALAJAFANQAGAOAAAOQAAAHgBAHIgFAOQgFANgLAKQgJAKgOAGIgOADIgPACQgHAAgHgCgAgRgrQgJAEgGAGQgGAHgEAIQgFAJAAAJQAAAKAFAIQAEAJAGAHQAGAGAJAEQAIAEAJAAQAJAAAJgEQAIgEAHgGQAGgHAEgJQAEgIAAgKQAAgJgEgJQgEgIgGgHQgHgGgIgEQgJgEgJAAQgJAAgIAEg");
	this.shape_15.setTransform(-96.6,3.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E46").s().p("AgFBIIgDAAIgCgDIgBgDIAAgwIgCgIIgEgHIgng9IAAgCQAAAAAAgBQAAAAAAgBQAAAAABgBQAAgBABAAIADgEIAGgBIAEgBIAFABIADACIAbAtIADACIADACIADgCIADgCIAcgtQAAAAAAgBQAAAAABgBQAAAAABAAQAAgBABAAIAFgBIAEABIAGABIADAEQABABAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAABIgBACIgnA9IgDAJIgCACIAAADIAAAxQgBAFgFABIgHABg");
	this.shape_16.setTransform(-111.1,3.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.youtakethecredit, new cjs.Rectangle(-123,-8.1,246.1,24.3), null);


(lib.whiterectanglefade = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ege2AqlMAAAhVJMA9tAAAMAAABVJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.whiterectanglefade, new cjs.Rectangle(-197.4,-272.4,395,545), null);


(lib.wellmakeuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AhLBYQgigiAAgyQAAg2AjgjQAhgkA1AAQAtAAAbAaQAaAZAAAtQAAANgEAGQgFAEgRAAIhZAAQgIAAgEgEQgEgDAAgHQAAgGAEgDQAEgEAHAAIAxAAIAMgCQADgBAAgGQAAgWgPgQQgQgPgUAAQgcAAgOAYQgNAYAAAjQgBAkAUAbQASAaAdAAQARAAAMgEQAMgEALgHIAJgHQAMgKAGAAQAFAAAEADQACAEAAAEQAAAHgFAIQgGAHgKAJQgUAQgTAIQgTAHgWAAQgxAAghgig");
	this.shape.setTransform(106.7,-23.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("ABMCrIgKgBQgKgEgWgdIgKgMIgEgGQg5hJgEAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAABgBAAIgBAKIAAAKIACAyQABAOAEAEIANAGQALAFAAAJQAAAJgMADQgMAEgeAAQgkAAgLgEQgMgEAAgKQAAgIAMgEIAGgDQAGgDADgLQACgMAAgbIAAgdIAAgkIAAgcIgChYQgBgVgEgEQgCgDgLgDIgIgCIgIgEIgCgHQAAgGAEgEQAFgEAQgGIAggIIAYgEQAHAAADAFQADAEAAALIgBAtIgCA9IAAA6IABAMQABAAAAABQAAAAABABQAAAAABAAQAAAAABAAIAKgFIARgOIAWgWQAGgHAAgEQAAgCgJgEQgIgFAAgHQAAgLAMgEQAMgEAhAAQAWAAALAEQAKAFAAAJQAAALgRAEQgRAEgHAEQgIAFgVAUIgDADIgIAJIgDAFQAAAEAVAbIACADIAoAxQARATAJAHQAGAEAPAFQAPAFAAAJQAAAKgLAFQgLAEgZAAg");
	this.shape_1.setTransform(82.1,-28.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AApBuIgMgMIgKAFQgdATgdAAQghAAgWgUQgUgUAAggQAAglAbgUQAbgVAwAAQAMAAAGADQAFAEAAAJQAAANgQAAQgWAAgOALQgPALAAAUQAAATANALQAMALAVAAQAVAAAKgKQAKgKAAgZIAAhYQAAgVgJgLQgIgLgRAAQgLAAgKAFQgKAFgJALIgFAGQgOASgQAAQgJAAgGgGQgFgGAAgKQAAgWAbgPQAbgPArAAQAZAAASAHQAUAHAKANQAHAJADAOQACAOAAAiIAABKQAAANACAHQADAHAEABIAIACQAPAEAAAIQgBALgPAJQgQAJgUAAQgLAAgMgMg");
	this.shape_2.setTransform(56,-23.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("ABXClQgMgEAAgKQAAgKAOgFIAKgGQAEgDACgKQACgKAAggIAAgMIgBhjIgBg7IgdBNQhFCzgPAAQgHAAgNgYQgOgZghhMIgzh1IgCBcIgBA/IACArQABALAEACIAKAGQAPAFAAAKQAAAJgMAFQgMAEgdAAQgaAAgLgEQgMgFAAgKQAAgIANgGQANgGABgFQADgLAEg8QADg8AAhJIAAgIQAAgYgCgJQgCgIgFgDIgLgFQgPgGAAgJQAAgKAKgDQALgEAiAAIAhABIAKACQAEADAQAqIAOAhIAGARQA5CMAEAAQAFAAAVgzQAVgxAdhSIAFgPQAIgaAHgHQAEgEAKgCIAfgCQAgAAAKAEQALADAAAKQAAAKgOAEIgGADQgHAEgCAJQgDAJAAAkIADCFQACA8ACAIQABAGALAEIAFABIAJAGQADADAAAGQAAAKgNAEQgNAEgnAAQgjAAgNgEg");
	this.shape_3.setTransform(22,-28.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AgnCoQgLgEAAgKQAAgHAJgEIAMgHQAEgEACgOIABguIAAglIAAgrIAAgSQAAg7gCgRQgCgRgFgDIgPgFQgOgEAAgIQAAgGAEgEQAFgEARgGIAfgIIAYgEQAGAAAEAFQACAEAAALIAAASQgDBTAABVIABBPQACARAEAFIANAGQALAFAAAJQAAAJgMADQgLAEgfAAQgjAAgLgEg");
	this.shape_4.setTransform(-18.9,-28.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AgnCoQgMgEAAgKQAAgHAKgEIAMgHQAEgEACgOIABguIAAglIAAgrIAAgSQAAg7gCgRQgCgRgFgDIgOgFQgPgEAAgIQAAgGAFgEQAEgEAQgGIAggIIAXgEQAIAAACAFQADAEAAALIAAASQgDBTAABVIABBPQACARAEAFIANAGQALAFAAAJQAAAJgMADQgMAEgeAAQgjAAgLgEg");
	this.shape_5.setTransform(-32,-28.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgDBEIgRhmIAAgDIAAgFQAAgMAFgGQAGgHAJAAQAKAAAGAHQAFAGAAAMIAAAFIAAAEIgRBlg");
	this.shape_6.setTransform(-42.2,-37.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AhMBYQghgiAAgyQAAg2AjgjQAhgkA1AAQAtAAAbAaQAaAZAAAtQAAANgEAGQgEAEgSAAIhZAAQgIAAgEgEQgEgDAAgHQAAgGAEgDQAEgEAHAAIAxAAIAMgCQADgBAAgGQAAgWgPgQQgQgPgUAAQgcAAgOAYQgOAYAAAjQAAAkAUAbQASAaAdAAQARAAAMgEQAMgEALgHIAJgHQAMgKAGAAQAFAAAEADQACAEAAAEQAAAHgFAIQgGAHgKAJQgUAQgTAIQgTAHgWAAQgxAAgigig");
	this.shape_7.setTransform(-58.5,-23.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AAgBSIgyiCQgPgqgJgUQgKgTgIgHIgNgFQgMgFAAgIQAAgKALgDQALgEAsAAQAsAAALAEQAKADAAAKQAAAJgSAGIgBABQgGACgDADQgCAEAAAFQAAAIALAgIAnBmIAQAlQAGAKACAAQAEAAAFgIIAPgiIAEgKQAwhzAAgPQAAgHgDgFQgDgFgIgDIgGgDQgNgFAAgJQAAgKAKgDQAIgEAnAAQAlAAAJAEQAKADAAAKQAAAJgNAFIgKAFQgRALgfBQIgTAwIgtBuIgIAVQgOAlgKAAQgMAAgjhagAhgCYIgDgHQgehBguh3IgVg5IgOgcQgGgJgIgFIgHgCQgOgFAAgJQAAgKALgDQAKgEAtAAQAtAAAKAEQALADAAAKQAAAJgTAGIgBABQgFACgDAEQgDADAAAFQAAAIAKAcIAnBnIASAqQAFAIADAAQAFAAAFgLIALgbQAFgQANAAQAOAAAAAQIgCAPIgfBKIgGASQgPAmgKAAQgIAAgIgUg");
	this.shape_8.setTransform(-95,-28.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wellmakeuse, new cjs.Rectangle(-153,-58.5,306.1,59.6), null);


(lib.wellmakethefeast = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgZAaQgLgLAAgPQAAgOALgKQALgLAOAAQAPAAAKALQALAKAAAOQAAAPgLALQgKALgPAAQgOAAgLgLg");
	this.shape.setTransform(98.4,40.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgMCMQgMgDgIgIQgIgIgDgMQgEgNAAgkIAAh8IgVAAIgHgCIgCgFIAAgHQAAgHAYgVIAKgIIAJgIQAYgVAJAAIAHACQACABAAAFIAAArIA1AAQAFAAADADQACACAAAGIAAAFQAAAHgDACQgCADgFAAIgxAAIgDACIgCAFIAAB0QAAAeAGAHQAEAIAOAAQAIAAALgDIAQgFQAFAAAEAEQADADAAAFQAAANgUALQgUAMgZABQgNAAgMgFg");
	this.shape_1.setTransform(83.7,29.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AgRB5IgZgEIgHAEIgIACIgEgBIgFgEQgIgGgGgTQgHgTAAgRQAAgHAEgFQAEgGAGAAQAKAAALATIAKAOQAHAKALAFQANAFANAAQAPAAAJgHQAJgIAAgNQAAgUgmgTIgNgGQglgSgNgPQgNgPAAgWQAAgfAVgTQAWgTAhAAIAQABIARADIALgFIAHgBQAMAAALASQAKATABAUQAAAIgFAFQgDAFgHAAQgFAAgFgFQgGgEgGgMQgKgOgIgGQgKgFgNAAQgMAAgJAHQgIAIAAAMQAAALAIAIQAIAIAdAPIACABQBCAfAAAmQAAAhgZAWQgaAWglAAg");
	this.shape_2.setTransform(65.1,32.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AAqBuIgNgMIgKAFQgcATgdAAQgjAAgUgUQgWgUAAggQAAglAbgUQAbgVAyAAQALAAAGADQAGAEgBAJQAAANgPAAQgXAAgOALQgOALAAAUQAAATAMALQAMALAVAAQAWAAAKgKQAJgKAAgZIAAhYQAAgVgIgLQgKgLgPAAQgMAAgKAFQgKAFgJALIgEAGQgPASgQAAQgJAAgFgGQgGgGAAgKQAAgWAbgPQAcgPAqAAQAZAAATAHQASAHAKANQAIAJACAOQADAOABAiIAABKQAAANACAHQACAHAFABIAHACQAOAEABAIQgBALgPAJQgPAJgWAAQgKAAgLgMg");
	this.shape_3.setTransform(42.9,32.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AhMBYQghgiAAgzQAAg1AigkQAjgjA0AAQAuAAAaAaQAaAZAAAtQAAAOgEAFQgEAEgSAAIhZAAQgIAAgEgEQgEgDAAgHQAAgGAEgDQAEgEAIAAIAwAAIAMgCQADgBAAgGQAAgWgQgQQgPgPgVAAQgcAAgNAYQgOAZAAAiQABAkASAbQATAaAdAAQARAAAMgEQAMgDALgIIAIgHQANgKAGAAQAFAAADAEQAEADAAAEQgBAGgFAIQgGAJgKAIQgVAQgSAIQgTAHgWAAQgxAAgigig");
	this.shape_4.setTransform(17.8,32.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("Ah3CnQgMgEAAgKQAAgJAMgFQAMgFADgDQADgFACgjIAChbIgChWQgCgkgDgEQgCgDgNgFQgMgGAAgJQAAgJAKgEQAMgDAoAAICOAAIAXgDIANgCIAFABIAFAEQAEAJAFAQQAEAQAAALQAAALgEAFQgEAGgHAAQgIAAgJgQIgIgLQgEgHgLgEQgLgEgPAAIggAAQgWAAgMACQgLADgEAGQgEAEgCAQIgCAsIAAATQABAMACACQABADAHAAIAmAAQASAAAIgFQAHgGACgOIABgEQADgZANAAQAJAAAEANQAFAMAAAuQAAArgEANQgEAMgKAAQgNAAgDgYIgBgEQgCgPgHgFQgIgFgSAAIglAAQgHAAgCAEQgCADgBAPIAAASIACBCQABAOAFADIAKAFQAOAGAAAJQABAKgNAEQgOAEgkAAQgmAAgNgEg");
	this.shape_5.setTransform(-8.3,26.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AhMBYQghgiAAgzQAAg1AigkQAigjA1AAQAtAAAbAaQAaAZAAAtQAAAOgEAFQgEAEgSAAIhZAAQgIAAgEgEQgEgDAAgHQAAgGAEgDQAEgEAIAAIAwAAIAMgCQADgBAAgGQAAgWgQgQQgOgPgWAAQgcAAgNAYQgOAZAAAiQABAkASAbQATAaAdAAQARAAAMgEQAMgDALgIIAIgHQAMgKAHAAQAFAAADAEQAEADAAAEQAAAGgGAIQgGAJgKAIQgVAQgSAIQgTAHgWAAQgxAAgigig");
	this.shape_6.setTransform(-48,32.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AAgCoQgLgDAAgKQAAgJALgEIAJgEQAGgDACgJQACgLAAgYQAAhMgKgSQgJgTgZAAQgLAAgLAIQgLAHgHAMQgFAKgCASQgCASAAAtQAAAZACAHQACAIAFACIAJAEQAMAEgBAJQAAAKgLADQgMADgeABQglgBgKgDQgMgEAAgKQAAgIAMgEIAFgDQAHgEACgJQADgKAAgZIAAgmIAAgkIgBhqQgCgZgEgGQgCgDgOgDQgNgFAAgIQgBgGAGgFQAGgEAUgHIAYgHIAVgCQAJgBADAFQADAFAAAKIAAAKIgCBdIAAAMIABAFIADACIAGgFIAIgKQALgLANgGQANgGAOAAQAoAAAUAaQAUAaAAA0IAAAWIAAAqIAAANQAAALADAGQACAFAFADIAGACQALAFAAAIQAAAKgLAEQgKADglABQgfgBgMgDg");
	this.shape_7.setTransform(-74.7,26.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AgMCMQgMgDgIgIQgIgIgDgMQgEgNAAgkIAAh8IgVAAIgHgCIgCgFIAAgHQAAgHAYgVIAKgIIAJgIQAYgVAJAAIAHACQACABAAAFIAAArIA1AAQAFAAADADQACACAAAGIAAAFQAAAHgDACQgCADgFAAIgxAAIgDACIgCAFIAAB0QAAAeAGAHQAEAIAOAAQAIAAALgDIAQgFQAFAAAEAEQADADAAAFQAAANgUALQgUAMgZABQgNAAgMgFg");
	this.shape_8.setTransform(-96.4,29.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AhLBYQgigiAAgyQAAg2AjgjQAhgkA1AAQAtAAAbAaQAaAZAAAtQAAANgEAGQgFAEgRAAIhZAAQgIAAgEgEQgEgDAAgHQAAgGAEgDQAEgEAHAAIAxAAIAMgCQADgBAAgGQAAgWgPgQQgQgPgUAAQgcAAgOAYQgNAYAAAjQgBAkAUAbQASAaAdAAQARAAAMgEQAMgEALgHIAJgHQAMgKAGAAQAFAAAEADQACAEAAAEQAAAHgFAIQgGAHgKAJQgUAQgTAIQgTAHgWAAQgxAAghgig");
	this.shape_9.setTransform(106.7,-23.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("ABMCrIgKgBQgKgEgWgdIgKgMIgEgGQg5hJgEAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAABgBAAIgBAKIAAAKIACAyQABAOAEAEIANAGQALAFAAAJQAAAJgMADQgMAEgeAAQgkAAgLgEQgMgEAAgKQAAgIAMgEIAGgDQAGgDADgLQACgMAAgbIAAgdIAAgkIAAgcIgChYQgBgVgEgEQgCgDgLgDIgIgCIgIgEIgCgHQAAgGAEgEQAFgEAQgGIAggIIAYgEQAHAAADAFQADAEAAALIgBAtIgCA9IAAA6IABAMQABAAAAABQAAAAABABQAAAAABAAQAAAAABAAIAKgFIARgOIAWgWQAGgHAAgEQAAgCgJgEQgIgFAAgHQAAgLAMgEQAMgEAhAAQAWAAALAEQAKAFAAAJQAAALgRAEQgRAEgHAEQgIAFgVAUIgDADIgIAJIgDAFQAAAEAVAbIACADIAoAxQARATAJAHQAGAEAPAFQAPAFAAAJQAAAKgLAFQgLAEgZAAg");
	this.shape_10.setTransform(82.1,-28.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AApBuIgMgMIgKAFQgdATgdAAQghAAgWgUQgUgUAAggQAAglAbgUQAbgVAwAAQAMAAAGADQAFAEAAAJQAAANgQAAQgWAAgOALQgPALAAAUQAAATANALQAMALAVAAQAVAAAKgKQAKgKAAgZIAAhYQAAgVgJgLQgIgLgRAAQgLAAgKAFQgKAFgJALIgFAGQgOASgQAAQgJAAgGgGQgFgGAAgKQAAgWAbgPQAbgPArAAQAZAAASAHQAUAHAKANQAHAJADAOQACAOAAAiIAABKQAAANACAHQADAHAEABIAIACQAPAEAAAIQgBALgPAJQgQAJgUAAQgLAAgMgMg");
	this.shape_11.setTransform(56,-23.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E46").s().p("ABXClQgMgEAAgKQAAgKAOgFIAKgGQAEgDACgKQACgKAAggIAAgMIgBhjIgBg7IgdBNQhFCzgPAAQgHAAgNgYQgOgZghhMIgzh1IgCBcIgBA/IACArQABALAEACIAKAGQAPAFAAAKQAAAJgMAFQgMAEgdAAQgaAAgLgEQgMgFAAgKQAAgIANgGQANgGABgFQADgLAEg8QADg8AAhJIAAgIQAAgYgCgJQgCgIgFgDIgLgFQgPgGAAgJQAAgKAKgDQALgEAiAAIAhABIAKACQAEADAQAqIAOAhIAGARQA5CMAEAAQAFAAAVgzQAVgxAdhSIAFgPQAIgaAHgHQAEgEAKgCIAfgCQAgAAAKAEQALADAAAKQAAAKgOAEIgGADQgHAEgCAJQgDAJAAAkIADCFQACA8ACAIQABAGALAEIAFABIAJAGQADADAAAGQAAAKgNAEQgNAEgnAAQgjAAgNgEg");
	this.shape_12.setTransform(22,-28.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E46").s().p("AgnCoQgLgEAAgKQAAgHAJgEIAMgHQAEgEACgOIABguIAAglIAAgrIAAgSQAAg7gCgRQgCgRgFgDIgPgFQgOgEAAgIQAAgGAEgEQAFgEARgGIAfgIIAYgEQAGAAAEAFQACAEAAALIAAASQgDBTAABVIABBPQACARAEAFIANAGQALAFAAAJQAAAJgMADQgLAEgfAAQgjAAgLgEg");
	this.shape_13.setTransform(-18.9,-28.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E46").s().p("AgnCoQgMgEAAgKQAAgHAKgEIAMgHQAEgEACgOIABguIAAglIAAgrIAAgSQAAg7gCgRQgCgRgFgDIgOgFQgPgEAAgIQAAgGAFgEQAEgEAQgGIAggIIAXgEQAIAAACAFQADAEAAALIAAASQgDBTAABVIABBPQACARAEAFIANAGQALAFAAAJQAAAJgMADQgMAEgeAAQgjAAgLgEg");
	this.shape_14.setTransform(-32,-28.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E46").s().p("AgDBEIgRhmIAAgDIAAgFQAAgMAFgGQAGgHAJAAQAKAAAGAHQAFAGAAAMIAAAFIAAAEIgRBlg");
	this.shape_15.setTransform(-42.2,-37.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E46").s().p("AhMBYQghgiAAgyQAAg2AjgjQAhgkA1AAQAtAAAbAaQAaAZAAAtQAAANgEAGQgEAEgSAAIhZAAQgIAAgEgEQgEgDAAgHQAAgGAEgDQAEgEAHAAIAxAAIAMgCQADgBAAgGQAAgWgPgQQgQgPgUAAQgcAAgOAYQgOAYAAAjQAAAkAUAbQASAaAdAAQARAAAMgEQAMgEALgHIAJgHQAMgKAGAAQAFAAAEADQACAEAAAEQAAAHgFAIQgGAHgKAJQgUAQgTAIQgTAHgWAAQgxAAgigig");
	this.shape_16.setTransform(-58.5,-23.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E46").s().p("AAgBSIgyiCQgPgqgJgUQgKgTgIgHIgNgFQgMgFAAgIQAAgKALgDQALgEAsAAQAsAAALAEQAKADAAAKQAAAJgSAGIgBABQgGACgDADQgCAEAAAFQAAAIALAgIAnBmIAQAlQAGAKACAAQAEAAAFgIIAPgiIAEgKQAwhzAAgPQAAgHgDgFQgDgFgIgDIgGgDQgNgFAAgJQAAgKAKgDQAIgEAnAAQAlAAAJAEQAKADAAAKQAAAJgNAFIgKAFQgRALgfBQIgTAwIgtBuIgIAVQgOAlgKAAQgMAAgjhagAhgCYIgDgHQgehBguh3IgVg5IgOgcQgGgJgIgFIgHgCQgOgFAAgJQAAgKALgDQAKgEAtAAQAtAAAKAEQALADAAAKQAAAJgTAGIgBABQgFACgDAEQgDADAAAFQAAAIAKAcIAnBnIASAqQAFAIADAAQAFAAAFgLIALgbQAFgQANAAQAOAAAAAQIgCAPIgfBKIgGASQgPAmgKAAQgIAAgIgUg");
	this.shape_17.setTransform(-95,-28.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wellmakethefeast, new cjs.Rectangle(-164.5,-58.5,329.1,115.1), null);


(lib.theturkeyuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgZAaQgLgLABgPQgBgPALgJQALgMAOAAQAPAAAKAMQAMAJAAAPQAAAPgMALQgKALgPAAQgOAAgLgLg");
	this.shape.setTransform(116.2,14);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AhrCbQgMgKAAgPQAAgLAJgJQAIgIALAAIALABIAHAGIAGAIQAGAKAFAAQAMgBAMgQQAMgSAAgSQAAgVgQgkIgDgGIglhRIgWguQgEgIgNgGIgBAAQgIgEgCgDQgDgDAAgFQAAgKAMgEQANgEAiAAQAiAAALAEQAMADAAAJIgCAIIgEAFIgIADQgJAEAAAEIAEASIATAuIATAsQAGALADAAQACABAGgLIAPglIARgvQAGgQAAgHQAAgGgNgHQgOgIAAgGQAAgIALgDQALgEAaAAQAcAAAKAEQAKADAAAJQAAAJgNAEIgKADQgNAHgPAoIgHASIgeBLQgmBhgYAdQgZAdgiAAQgRAAgLgJg");
	this.shape_1.setTransform(98.2,10.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AhLBYQgigiAAgyQAAg2AjgjQAhgkA1AAQAtAAAbAaQAaAZAAAtQAAANgEAGQgFAEgRAAIhZAAQgIAAgEgEQgEgDAAgHQAAgGAEgDQAEgEAHAAIAxAAIAMgCQADgBAAgGQAAgWgPgQQgQgPgUAAQgcAAgOAYQgNAYAAAjQgBAkAUAbQASAaAdAAQARAAAMgEQAMgEALgHIAJgHQAMgKAGAAQAFAAAEADQACAEAAAEQABAHgGAIQgGAHgKAJQgVAQgSAIQgTAHgWAAQgxAAghgig");
	this.shape_2.setTransform(74,5.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("ABMCrIgKgBQgKgEgWgdIgKgMIgEgGQg5hJgEAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAABgBAAIgBAKIAAAKIACAyQABAOAEAEIANAGQALAFAAAJQAAAJgMADQgMAEgeAAQgkAAgLgEQgMgEAAgKQAAgIAMgEIAGgDQAGgDADgLQACgMAAgbIAAgdIAAgkIAAgcIgChYQgBgVgEgEQgCgDgLgDIgIgCIgIgEIgCgHQAAgGAEgEQAFgEAQgGIAggIIAYgEQAHAAADAFQADAEAAALIgBAtIgCA9IAAA6IABAMQABAAAAABQAAAAABABQAAAAABAAQAAAAABAAIAKgFIARgOIAWgWQAGgHAAgEQAAgCgJgEQgIgFAAgHQAAgLAMgEQAMgEAhAAQAWAAALAEQAKAFAAAJQAAALgRAEQgRAEgHAEQgIAFgVAUIgDADIgIAJIgDAFQAAAEAVAbIACADIAoAxQARATAJAHQAGAEAPAFQAPAFAAAJQAAAKgLAFQgLAEgZAAg");
	this.shape_3.setTransform(49.4,0);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AhGB0QgLgEAAgKQgBgIALgEIAHgDQAGgDADgIQACgIAAgRIAAgQIAAgTIAAgOQgBgqgBgNQgDgNgFgDIgKgEQgOgFAAgHQAAgGAEgEQAFgEAKgEIAggKIAUgEQAMAAADAfIABAFIABABQAMgTANgKQAOgKANAAQAPAAALAKQAJAKAAAQQAAARgIAJQgHAJgNAAIgMgCIgKgHIgFgJQgCgGgDAAQgRAAgFAWQgGAXAABGQAAAUACALQACAKAHADIAJADQAOAEAAAKQAAAIgNAEQgNAEgfAAQgjAAgMgEg");
	this.shape_4.setTransform(27.1,5.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AAzB3QgDgEAAgIIAAgQIgBgBIgBgBQgCAAgGAGIgDAEQgLALgOAGQgOAFgRAAQgSAAgPgGQgPgHgLgMQgLgNgEgTQgFgTAAgxIAAgQIABgRIAAgFQAAgTgDgGQgDgFgIgDIgKgDQgNgEAAgIQAAgGAFgEQAFgEAQgFIAggJIAZgDQAGAAADAFQADAEAAALIgBAJIgCBXQAAAvAKASQAKASAXAAQAaAAAMgXQAMgYAAg4IAAgSQAAgSgDgGQgDgFgIgDIgJgDQgNgEAAgIQAAgGAFgDQAEgEAQgGIAggJIAYgDQAHAAADAEQADAFAAALIgBANIgCBfIAAAoIACAPQABAKAMAFIAFABQANAEAAAIQAAAFgEAFQgEADgKAEIgiALQgQAEgIAAQgHAAgDgDg");
	this.shape_5.setTransform(3.4,5.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgxCmQgNgEAAgKQAAgJANgFQAMgFADgDQACgEACgnIABhuIAAg+IgDglQAAgGgEgCQgEgCgKAAIgKAAQgQAAgJADQgJAEgHAJIgHAQIgHAQIgHAHQgEADgEAAQgHAAgDgGQgDgGAAgPQAAgfAHgSQAHgTALAAIADAAQASADAdAAICJAAQAcAAATgDIACAAQAMAAAHATQAHASAAAfQAAAOgDAHQgDAGgIAAIgIgDIgGgHIgHgQIgIgQQgGgJgJgEQgKgDgQAAIgJAAQgKAAgEACQgEACgBAGIgCAmIAAA9IABBuQABAnADAEQACADANAFQANAFAAAJQAAAKgOAEQgNAEgkAAQgkAAgNgEg");
	this.shape_6.setTransform(-25.5,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AhMBYQghgiAAgyQAAg2AigjQAjgkA0AAQAuAAAaAaQAaAZAAAtQAAANgEAGQgEAEgSAAIhZAAQgIAAgEgEQgEgDAAgHQAAgGAEgDQAEgEAHAAIAxAAIAMgCQADgBAAgGQAAgWgQgQQgPgPgVAAQgcAAgNAYQgOAYAAAjQABAkASAbQATAaAdAAQARAAAMgEQAMgEALgHIAIgHQANgKAGAAQAFAAADADQAEAEAAAEQgBAHgFAIQgGAHgKAJQgVAQgSAIQgTAHgWAAQgxAAgigig");
	this.shape_7.setTransform(-65.9,5.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AAgCoQgLgEAAgIQAAgKALgEIAJgDQAGgEACgKQACgKAAgYQAAhMgKgSQgIgTgaAAQgLAAgLAIQgMAIgGALQgFAKgCASQgCASAAAtQAAAZACAHQACAIAFADIAJADQAMAEgBAKQAAAIgLAEQgMAEgeAAQglAAgKgEQgMgEAAgKQAAgIAMgEIAGgDQAGgDADgKQACgKAAgZIAAgnIAAgjIgBhqQgCgagEgFQgCgCgOgFQgNgDAAgJQgBgGAGgEQAGgFAUgIIAYgGIAVgDQAJAAADAFQADAFAAAKIAAAKIgCBdIAAALIABAGIADACIAGgFIAIgKQALgLANgGQANgGAPAAQAnAAAUAaQAUAaAAA0IAAAWIAAAqIAAANQABAMACAFQACAFAFADIAGACQAMAFgBAIQAAAKgLAEQgLAEgkAAQgfAAgMgEg");
	this.shape_8.setTransform(-92.6,0);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AgMCMQgMgDgIgIQgIgHgDgNQgEgNAAgkIAAh8IgVAAIgHgCIgCgGIAAgFQAAgIAYgVIAKgIIAJgIQAYgVAJgBIAHADQACACAAADIAAAsIA1AAQAFAAADACQACADAAAGIAAAFQAAAHgDACQgCADgFAAIgxAAIgDACIgCAFIAAB0QAAAeAGAHQAEAJAOgBQAIAAALgDIAQgFQAFABAEADQADACAAAFQAAANgUAMQgUANgZAAQgNgBgMgEg");
	this.shape_9.setTransform(-114.3,3.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.theturkeyuse, new cjs.Rectangle(-147.5,-29.7,295.1,59.6), null);


(lib.thestuffinguse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgZAaQgLgLABgPQgBgPALgJQALgMAOAAQAPAAAKAMQAMAJAAAPQAAAPgMALQgKALgPAAQgOAAgLgLg");
	this.shape.setTransform(123,14);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AhWCYQgegSAAgaQAAgLAHgIQAFgHANgBQALAAAFAGQAFAFAEAMQAFAQAPALQAOAKAdgBQAeABAVgMQAVgNAAgSQAAgKgIgHQgIgGgPAAIgbACIgjACQgqAAgWgOQgXgOABgTQgBgLAJgMQAIgKARgLQgOgMgHgOQgHgPAAgTQAAgmAdgZQAcgaAtAAIAXADIAkAHQAJAAALgFQAJgEAPgKIAIAHIACAIQABAKgIAJQgHAJgOAHIAHATIACATQAAAngcAZQgdAXgsAAIgagBIgVgFIgHAIIgDAJQAAAMALAEQALAGAYAAIAigDIAlgDQAgAAARAOQASANAAAZQAAAlglAZQglAZg3AAQgtAAgdgTgAglh0QgNAQAAAXQAAAXAMAPQAMAPASAAQAUAAANgPQANgPAAgXQAAgYgNgPQgMgPgUAAQgTAAgLAPg");
	this.shape_1.setTransform(105,9.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AAfB0QgLgDAAgJQAAgJALgFIAJgDQAGgDACgKQACgLAAgZQAAhKgKgTQgJgTgYAAQgMAAgMAIQgLAIgGAMQgFAKgCASQgCASAAAuQAAAXACAHQACAIAFADIAJADQALAFAAAJQAAAJgLADQgMAEgeAAQgkAAgMgEQgLgEAAgKQAAgIALgEIAHgDQAFgDADgIQACgIAAgRIAAgQIAAgTIAAgXQAAglgCgLQgCgMgFgCIgKgEQgOgFgBgHQABgGAEgEQAFgEAJgEIAigLIAZgEQAGAAADAEQADADgBAIIAAAQIABACIABAAIACAAIABAAIAFgFIAFgFQAZgYAdAAQARAAAPAIQAQAHALANQAKAMAFASQAFASAAAmIAAAeIAAAPIAAAOQAAAQACAHQACAHAGADIAGADQAMAEAAAIQAAAKgMAEQgKAEgkAAQghAAgLgEg");
	this.shape_2.setTransform(77.8,5.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AgpCnQgLgEAAgKQAAgIALgEIAGgDQAGgDADgIQACgIAAgRIAAgQIAAgTIAAgYQAAglgCgKQgCgMgFgCIgLgEQgOgFAAgHQAAgGAFgEQAEgEAKgEIAjgLIAYgFQAHAAADAFQACAEAAALIAAAOIAAALIgCA6IAAACIgBA5QAAAWACAKQACAJAFADIAJADQAMAFAAAJQAAAJgLADQgMAEgeAAQgjAAgMgEgAgch1QgKgIAAgNQAAgNALgJQALgKAQAAQAOAAAKAJQAKAIAAANQAAANgLAJQgLAJgPAAQgPAAgKgIg");
	this.shape_3.setTransform(57.2,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AhBCnQgLgDAAgJQAAgIALgEIAFgDQAGgCACgIQADgIAAgTIAAgXIAAhwIgbAAQgFgBgCgCQgCgDAAgGIAAgFQAAgGACgDQACgCAGAAIAYAAIgCgTIgBgQQAAgkAVgTQAWgVAlAAQAbAAARANQARALAAATQAAALgHAGQgFAGgMAAQgHAAgGgEQgGgDgEgHIgFgIQgIgQgOgBQgJAAgEAGQgGAGAAAJIAGAaQAEAUABARIAhAAQAHAAABACQACACABAHIAAAFQgBAGgCADQgCACgGABIghAAIAAB3QAAAeACAKQACAIAFADIAJADQAOAFgBAKQAAAIgLAEQgLAEghAAQgjgBgLgEg");
	this.shape_4.setTransform(46.1,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AhBCnQgMgDAAgJQAAgIAMgEIAFgDQAGgCACgIQACgIAAgTIAAgXIAAhwIgaAAQgFgBgCgCQgDgDAAgGIAAgFQAAgGADgDQACgCAFAAIAZAAIgCgTIgBgQQAAgkAVgTQAWgVAmAAQAaAAARANQAQALABATQgBALgFAGQgHAGgLAAQgIAAgFgEQgGgDgEgHIgEgIQgJgQgOgBQgIAAgFAGQgFAGgBAJIAGAaQAEAUAAARIAiAAQAHAAABACQACACAAAHIAAAFQAAAGgCADQgCACgGABIghAAIAAB3QAAAeACAKQABAIAFADIAJADQAOAFABAKQAAAIgMAEQgMAEggAAQgjgBgLgEg");
	this.shape_5.setTransform(32.8,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AAzB3QgDgEAAgIIAAgQIgBgBIgBgBQgCAAgGAGIgDAEQgLALgOAGQgOAFgRAAQgSAAgPgGQgPgHgLgMQgLgNgEgTQgFgTAAgxIAAgQIABgRIAAgFQAAgTgDgGQgDgFgIgDIgKgDQgNgEAAgIQAAgGAFgEQAFgEAQgFIAggJIAZgDQAGAAADAFQADAEAAALIgBAJIgCBXQAAAvAKASQAKASAXAAQAaAAAMgXQAMgYAAg4IAAgSQAAgSgDgGQgDgFgIgDIgJgDQgNgEAAgIQAAgGAFgDQAEgEAQgGIAggJIAYgDQAHAAADAEQADAFAAALIgBANIgCBfIAAAoIACAPQABAKAMAFIAFABQANAEAAAIQAAAFgEAFQgEADgKAEIgiALQgQAEgIAAQgHAAgDgDg");
	this.shape_6.setTransform(10,5.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AgMCMQgMgDgIgIQgIgHgDgNQgEgNAAgkIAAh8IgVAAIgHgCIgCgGIAAgFQAAgIAYgVIAKgIIAJgIQAYgVAJgBIAHADQACACAAADIAAAsIA1AAQAFAAADACQACADAAAGIAAAFQAAAHgDACQgCADgFAAIgxAAIgDACIgCAFIAAB0QAAAeAGAHQAEAJAOgBQAIAAALgDIAQgFQAFABAEADQADACAAAFQAAANgUAMQgUANgZAAQgNgBgMgEg");
	this.shape_7.setTransform(-11.8,3.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("Ag5CpQgagGgRgKQgJgFgGgUQgGgVAAgZQAAgMAEgFQAEgGAIAAQAKAAAMAWIAGAJQAOAaASAMQARAMAZAAQAZAAASgPQARgQABgVQgBgihFgdIgHgEQg5gYgSgVQgTgUAAgiQAAgqAfgbQAfgbAxAAIAbADIAhAHIAKgGIAHgCQAGAAAFADQAEAEAFAJQAIAPAEAPQAFAPAAAMQAAAHgEAFQgEAFgGAAQgMAAgMgRIgEgFQgNgSgPgIQgQgIgUAAQgZAAgPAMQgPANAAAUQAAAUAMAMQANANAxAWIAKADQAqASATAQQAMAMAHAPQAHAQAAATQAAAwghAaQgiAbg6AAQgcAAgagFg");
	this.shape_8.setTransform(-33.8,0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AhLBYQgigiAAgyQAAg2AjgjQAhgkA1AAQAtAAAbAaQAaAZAAAtQAAANgEAGQgFAEgRAAIhZAAQgIAAgEgEQgEgDAAgHQAAgGAEgDQAEgEAIAAIAwAAIAMgCQADgBAAgGQAAgWgQgQQgOgPgWAAQgbAAgOAYQgNAYAAAjQgBAkAUAbQASAaAdAAQARAAAMgEQAMgEALgHIAIgHQAMgKAHAAQAFAAADADQADAEAAAEQABAHgGAIQgGAHgKAJQgVAQgSAIQgTAHgWAAQgxAAghgig");
	this.shape_9.setTransform(-72.6,5.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AAhCoQgMgEAAgIQAAgKAMgEIAJgDQAFgEACgKQACgKAAgYQAAhMgJgSQgKgTgZAAQgLAAgLAIQgMAIgGALQgFAKgCASQgCASAAAtQAAAZACAHQACAIAFADIAIADQANAEAAAKQAAAIgMAEQgMAEgdAAQgmAAgLgEQgLgEAAgKQAAgIALgEIAGgDQAHgDACgKQADgKAAgZIAAgnIAAgjIgBhqQgCgagDgFQgDgCgOgFQgOgDAAgJQAAgGAGgEQAGgFAVgIIAXgGIAWgDQAHAAAEAFQADAFAAAKIgBAKIgCBdIAAALIACAGIADACIAFgFIAIgKQAMgLANgGQANgGAOAAQApAAATAaQAUAaAAA0IAAAWIAAAqIAAANQAAAMACAFQADAFAFADIAGACQALAFAAAIQABAKgLAEQgMAEglAAQgeAAgLgEg");
	this.shape_10.setTransform(-99.3,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AgMCMQgMgDgIgIQgIgHgDgNQgEgNAAgkIAAh8IgVAAIgHgCIgCgGIAAgFQAAgIAYgVIAKgIIAJgIQAYgVAJgBIAHADQACACAAADIAAAsIA1AAQAFAAADACQACADAAAGIAAAFQAAAHgDACQgCADgFAAIgxAAIgDACIgCAFIAAB0QAAAeAGAHQAEAJAOgBQAIAAALgDIAQgFQAFABAEADQADACAAAFQAAANgUAMQgUANgZAAQgNgBgMgEg");
	this.shape_11.setTransform(-121,3.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thestuffinguse, new cjs.Rectangle(-140,-29.7,280,59.6), null);


(lib.thesidesuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgZAaQgLgLAAgPQAAgPALgJQALgMAOAAQAPAAAKAMQALAJAAAPQAAAPgLALQgKALgPAAQgOAAgLgLg");
	this.shape.setTransform(97.6,14);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgRB5IgZgEIgHAEIgIACIgEgBIgFgEQgIgGgGgTQgHgTAAgRQAAgHAEgFQAEgGAGAAQAKAAALATIAKAOQAHAKALAFQANAFANAAQAPAAAJgHQAJgIAAgNQAAgUgmgTIgNgGQglgSgNgPQgNgPAAgWQAAgfAVgTQAWgTAhAAIAQABIARADIALgFIAHgBQAMAAALASQAKATABAUQAAAIgFAFQgDAFgHAAQgFAAgFgFQgGgEgGgMQgKgOgIgGQgKgFgNAAQgMAAgJAHQgIAIAAAMQAAALAIAIQAIAIAdAPIACABQBCAfAAAmQAAAhgZAWQgaAWglAAg");
	this.shape_1.setTransform(80.9,5.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AhMBYQghgiAAgyQAAg2AigjQAjgkA0AAQAuAAAaAaQAaAZAAAtQAAANgEAGQgFAEgRAAIhZAAQgIAAgEgEQgEgDAAgHQAAgGAEgDQAEgEAIAAIAwAAIAMgCQADgBAAgGQAAgWgQgQQgOgPgWAAQgcAAgNAYQgNAYgBAjQABAkASAbQATAaAdAAQARAAAMgEQAMgEALgHIAIgHQAMgKAHAAQAFAAADADQADAEABAEQAAAHgGAIQgGAHgKAJQgUAQgTAIQgTAHgWAAQgxAAgigig");
	this.shape_2.setTransform(58.5,5.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AhmCOQgcggABgyQAAg5AfgkQAggjAygBIAQADQAHACAFAFQADAFAAAGQAAAMgPAAIgHAAIgFgBQgaAAgQAWQgPAUgBAlQAAAoARAYQASAZAZAAQAZAAANgOQAOgNAAgaIAAhAIAAhrQAAgRgDgHQgEgGgJgDIgFgBQgPgFAAgIQAAgGAGgFQAFgFASgGIAagIIAWgCQAIAAAEAEQADAFAAAKIgBAMIgCCQIABBiQACAWAEADIAQAGQANACAAAIQAAAMgjAKIgXAGIgSACQgGABgDgEQgDgEAAgHIAAgMIgBgEIgBgCIgHAFIgKAHQgOAMgMAEQgOAFgOAAQgsAAgcgfg");
	this.shape_3.setTransform(33.1,0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AgpCnQgLgEAAgKQAAgIALgEIAGgDQAGgDADgIQACgIAAgRIAAgQIAAgTIAAgYQAAglgCgKQgCgMgFgCIgLgEQgOgFAAgHQAAgGAFgEQAEgEAKgEIAjgLIAYgFQAHAAADAFQACAEAAALIAAAOIAAALIgCA6IAAACIgBA5QAAAWACAKQACAJAFADIAJADQAMAFAAAJQAAAJgLADQgMAEgeAAQgjAAgMgEgAgch1QgKgIAAgNQAAgNALgJQALgKAQAAQAOAAAKAJQAKAIAAANQAAANgLAJQgLAJgPAAQgPAAgKgIg");
	this.shape_4.setTransform(11.7,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("Ag6CpQgZgGgRgKQgJgFgGgUQgGgVAAgZQAAgMAEgFQAEgGAIAAQALAAALAWIAGAJQAPAaARAMQARAMAYAAQAaAAARgPQASgQAAgVQAAgihFgdIgHgEQg4gYgTgVQgTgUAAgiQAAgqAfgbQAfgbAxAAIAbADIAgAHIAKgGIAIgCQAGAAAEADQAFAEAFAJQAIAPAFAPQAEAPAAAMQAAAHgDAFQgFAFgGAAQgMAAgMgRIgEgFQgNgSgPgIQgPgIgVAAQgZAAgPAMQgPANAAAUQAAAUAMAMQANANAxAWIALADQApASATAQQANAMAGAPQAHAQAAATQAAAwghAaQghAbg8AAQgcAAgagFg");
	this.shape_5.setTransform(-8.4,0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AhMBYQghgiAAgyQAAg2AigjQAjgkA0AAQAuAAAaAaQAaAZAAAtQAAANgEAGQgFAEgRAAIhZAAQgIAAgEgEQgEgDAAgHQAAgGAEgDQAEgEAIAAIAwAAIAMgCQADgBAAgGQAAgWgQgQQgOgPgWAAQgcAAgNAYQgOAYAAAjQABAkASAbQATAaAdAAQARAAAMgEQAMgEALgHIAIgHQAMgKAHAAQAFAAADADQADAEABAEQAAAHgGAIQgGAHgKAJQgUAQgTAIQgTAHgWAAQgxAAgigig");
	this.shape_6.setTransform(-47.2,5.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AAgCoQgLgEAAgIQAAgKALgEIAJgDQAGgEACgKQACgKAAgYQAAhMgKgSQgJgTgZAAQgLAAgLAIQgLAIgHALQgFAKgCASQgCASAAAtQAAAZACAHQACAIAFADIAJADQALAEABAKQAAAIgMAEQgMAEgeAAQglAAgKgEQgMgEAAgKQAAgIAMgEIAFgDQAHgDACgKQADgKAAgZIAAgnIAAgjIgBhqQgCgagDgFQgDgCgOgFQgNgDAAgJQgBgGAGgEQAGgFAUgIIAYgGIAVgDQAJAAADAFQADAFAAAKIAAAKIgDBdIAAALIACAGIADACIAGgFIAHgKQAMgLANgGQANgGAOAAQAoAAAUAaQAUAaAAA0IAAAWIAAAqIAAANQAAAMACAFQADAFAFADIAGACQALAFAAAIQABAKgMAEQgLAEgkAAQgfAAgMgEg");
	this.shape_7.setTransform(-73.9,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AgMCMQgMgDgIgIQgIgHgDgNQgEgNAAgkIAAh8IgVAAIgHgCIgCgGIAAgFQAAgIAYgVIAKgIIAJgIQAYgVAJgBIAHADQACACAAADIAAAsIA1AAQAFAAADACQACADAAAGIAAAFQAAAHgDACQgCADgFAAIgxAAIgDACIgCAFIAAB0QAAAeAGAHQAEAJAOgBQAIAAALgDIAQgFQAFABAEADQADACAAAFQAAANgUAMQgUANgZAAQgNgBgMgEg");
	this.shape_8.setTransform(-95.6,3.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thesidesuse, new cjs.Rectangle(-128,-29.7,256.1,59.6), null);


(lib.thedessertsuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgZAaQgKgLAAgPQAAgPAKgJQAKgMAPAAQAPAAALAMQAKAJABAPQgBAPgKALQgLALgPAAQgPAAgKgLg");
	this.shape.setTransform(131.3,14);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgRB5IgZgEIgHAEIgHACIgFgBIgFgEQgHgGgIgTQgGgTAAgRQAAgHAEgFQAEgGAGAAQALAAAKATIAJAOQAIAKAMAFQAMAFAMAAQAQAAAJgHQAJgIAAgNQAAgUgmgTIgOgGQgkgSgNgPQgNgPAAgWQAAgfAWgTQAUgTAjAAIAPABIARADIALgFIAHgBQALAAALASQALATAAAUQAAAIgDAFQgEAFgGAAQgGAAgFgFQgFgEgIgMQgIgOgKgGQgJgFgNAAQgNAAgIAHQgJAIAAAMQAAALAJAIQAIAIAdAPIADABQBBAfAAAmQAAAhgZAWQgZAWgmAAg");
	this.shape_1.setTransform(114.6,5.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AgMCMQgMgDgIgIQgIgHgDgNQgEgNAAgkIAAh8IgVAAIgHgCIgCgGIAAgFQAAgIAYgVIAKgIIAJgIQAYgVAJgBIAHADQACACAAADIAAAsIA1AAQAFAAADACQACADAAAGIAAAFQAAAHgDACQgCADgFAAIgxAAIgDACIgCAFIAAB0QAAAeAGAHQAEAJAOgBQAIAAALgDIAQgFQAFABAEADQADACAAAFQAAANgUAMQgUANgZAAQgNgBgMgEg");
	this.shape_2.setTransform(96.4,3.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AhGB0QgLgEAAgKQgBgIALgEIAHgDQAGgDADgIQACgIAAgRIAAgQIAAgTIAAgOQAAgqgCgNQgCgNgFgDIgLgEQgOgFAAgHQAAgGAEgEQAEgEALgEIAggKIAUgEQALAAAEAfIABAFIABABQAMgTAOgKQANgKANAAQAPAAALAKQAJAKAAAQQAAARgHAJQgIAJgNAAIgMgCIgKgHIgFgJQgCgGgDAAQgRAAgFAWQgGAXAABGQAAAUACALQACAKAHADIAJADQAOAEAAAKQAAAIgNAEQgNAEgfAAQgkAAgLgEg");
	this.shape_3.setTransform(79.6,5.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AhLBYQgigiAAgyQAAg2AjgjQAhgkA1AAQAtAAAbAaQAaAZAAAtQAAANgEAGQgFAEgRAAIhZAAQgIAAgEgEQgEgDAAgHQAAgGAEgDQAEgEAHAAIAxAAIAMgCQADgBAAgGQAAgWgPgQQgQgPgUAAQgcAAgOAYQgNAYAAAjQgBAkAUAbQASAaAdAAQARAAAMgEQAMgEALgHIAJgHQAMgKAGAAQAFAAAEADQACAEAAAEQABAHgGAIQgGAHgKAJQgVAQgSAIQgTAHgWAAQgxAAghgig");
	this.shape_4.setTransform(57.8,5.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AgRB5IgZgEIgHAEIgIACIgEgBIgFgEQgIgGgGgTQgHgTAAgRQAAgHAEgFQAEgGAGAAQALAAALATIAJAOQAGAKANAFQAMAFANAAQAPAAAJgHQAJgIAAgNQAAgUgmgTIgNgGQglgSgNgPQgNgPAAgWQAAgfAVgTQAWgTAhAAIAQABIARADIALgFIAHgBQAMAAAKASQAMATAAAUQAAAIgFAFQgDAFgHAAQgFAAgFgFQgGgEgGgMQgKgOgIgGQgKgFgNAAQgMAAgJAHQgJAIABAMQgBALAJAIQAJAIAcAPIACABQBCAfAAAmQAAAhgZAWQgaAWglAAg");
	this.shape_5.setTransform(35.2,5.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgRB5IgZgEIgHAEIgHACIgFgBIgFgEQgHgGgIgTQgGgTAAgRQAAgHAEgFQAEgGAGAAQALAAAKATIAJAOQAIAKALAFQANAFAMAAQAQAAAJgHQAJgIAAgNQAAgUgmgTIgOgGQgkgSgNgPQgNgPAAgWQAAgfAWgTQAUgTAjAAIAPABIARADIALgFIAHgBQALAAALASQAMATgBAUQAAAIgDAFQgEAFgGAAQgGAAgFgFQgFgEgIgMQgJgOgJgGQgJgFgNAAQgNAAgIAHQgJAIAAAMQAAALAJAIQAIAIAdAPIADABQBBAfAAAmQAAAhgZAWQgaAWglAAg");
	this.shape_6.setTransform(15,5.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AhMBYQghgiAAgyQAAg2AigjQAjgkA0AAQAuAAAaAaQAaAZAAAtQAAANgEAGQgEAEgSAAIhZAAQgIAAgEgEQgEgDAAgHQAAgGAEgDQAEgEAHAAIAxAAIAMgCQADgBAAgGQAAgWgPgQQgQgPgUAAQgdAAgNAYQgOAYAAAjQAAAkATAbQATAaAdAAQARAAAMgEQAMgEALgHIAJgHQALgKAHAAQAFAAAEADQADAEAAAEQgBAHgFAIQgGAHgKAJQgVAQgSAIQgTAHgWAAQgxAAgigig");
	this.shape_7.setTransform(-7.3,5.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AgyCoIgdAAIgUAAIgTABQgdAAgJgEQgJgEAAgKQAAgJANgFQAMgFACgDQADgFACgjIAChaIgChWQgCgkgDgFQgCgDgMgFQgNgFAAgJQAAgKAKgEQAKgDAcAAIAUAAIAYAAIAfAAIAagBQBXAAAwAtQAvAtAABSQAABRgxAqQgwAqhdAAgAgziEQgKADgDAIQgDAIgCAbIgCBIIACBZQACAkADAIQACAHAQAFQAPAFAWAAQA1AAAbghQAaggAAhCQAAhEgeglQgfgkg5AAQgTAAgLAEg");
	this.shape_8.setTransform(-37.9,0.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AhLBYQgigiAAgyQAAg2AjgjQAhgkA1AAQAtAAAbAaQAaAZAAAtQAAANgEAGQgFAEgRAAIhZAAQgIAAgEgEQgEgDAAgHQAAgGAEgDQAEgEAHAAIAxAAIAMgCQADgBAAgGQAAgWgPgQQgQgPgUAAQgcAAgOAYQgNAYAAAjQgBAkAUAbQASAaAdAAQARAAAMgEQAMgEALgHIAJgHQAMgKAGAAQAFAAAEADQACAEAAAEQAAAHgFAIQgGAHgKAJQgUAQgTAIQgTAHgWAAQgxAAghgig");
	this.shape_9.setTransform(-80.9,5.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AAhCoQgMgEAAgIQAAgKAMgEIAJgDQAFgEACgKQACgKAAgYQAAhMgJgSQgJgTgZAAQgMAAgLAIQgMAIgGALQgFAKgCASQgCASAAAtQAAAZACAHQACAIAFADIAIADQAMAEAAAKQABAIgMAEQgLAEgeAAQglAAgMgEQgLgEAAgKQAAgIALgEIAHgDQAGgDADgKQACgKAAgZIAAgnIAAgjIgBhqQgCgagEgFQgCgCgOgFQgOgDAAgJQABgGAFgEQAGgFAVgIIAXgGIAWgDQAHAAAEAFQADAFAAAKIgBAKIgCBdIAAALIACAGIADACIAFgFIAIgKQANgLANgGQAMgGAPAAQAoAAATAaQAUAaAAA0IAAAWIABAqIAAANQAAAMABAFQADAFAFADIAGACQAMAFAAAIQgBAKgKAEQgLAEgmAAQgeAAgLgEg");
	this.shape_10.setTransform(-107.6,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AgMCMQgMgDgIgIQgIgHgDgNQgEgNAAgkIAAh8IgVAAIgHgCIgCgGIAAgFQAAgIAYgVIAKgIIAJgIQAYgVAJgBIAHADQACACAAADIAAAsIA1AAQAFAAADACQACADAAAGIAAAFQAAAHgDACQgCADgFAAIgxAAIgDACIgCAFIAAB0QAAAeAGAHQAEAJAOgBQAIAAALgDIAQgFQAFABAEADQADACAAAFQAAANgUAMQgUANgZAAQgNgBgMgEg");
	this.shape_11.setTransform(-129.3,3.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thedessertsuse, new cjs.Rectangle(-154,-29.7,308.1,59.6), null);


(lib.ordernowcta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAYAxIgYhOIAAAAIgXBOIgPAAIgdhiIAPAAIAWBOIAAAAIAXhOIAPAAIAXBOIAAAAIAWhOIAPAAIgdBig");
	this.shape.setTransform(37.1,-1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgKAzIgKgDQgJgEgIgGQgHgIgEgJQgDgKAAgLQAAgLADgKQAEgJAHgHQAIgGAJgFIAKgCIAKgBQALAAAKADIAJAFIAIAGQAHAHAEAJQADAKAAALQAAALgDAKQgEAJgHAIIgIAGIgJAEQgKAEgLAAIgKgBgAgOgkQgIADgFAGQgEAFgDAHQgDAIAAAHQAAAIADAIQADAGAEAGQAFAGAIADQAGACAIAAQAJAAAGgCQAHgDAGgGQAEgGADgGQADgIAAgIQAAgHgDgIQgDgHgEgFQgGgGgHgDQgGgDgJAAQgIAAgGADg");
	this.shape_1.setTransform(24.3,-1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAYAxIgzhQIAABQIgOAAIAAhiIASAAIAzBOIAAhOIAOAAIAABig");
	this.shape_2.setTransform(13,-1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AATAxIgZgsIgOAAIAAAsIgOAAIAAhiIAgAAQAGAAAGACQAHACAEACQAFADADAGQADAFAAAIQAAALgHAGQgDAEgFABIgJADIAbAtgAgUgFIAQAAIAIgBIAHgDQADgCACgDQACgDAAgEQAAgEgCgDIgFgGQgDgCgEAAIgHgBIgRAAg");
	this.shape_3.setTransform(0.2,-1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AggAxIAAhiIA/AAIAAANIgxAAIAAAdIAuAAIAAALIguAAIAAAhIAzAAIAAAMg");
	this.shape_4.setTransform(-8.4,-1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgrAxIAAhiIAiAAQAJAAAJADQAKADAIAGQAHAGAFAJIAEAKIABAMIgBAMIgEAKIgFAIIgHAIQgIAFgKADQgLADgHAAgAgdAmIASAAQAIgBAHgCQAIgDAFgEQAGgFADgHIACgHIABgJIgBgHIgCgJQgDgGgGgFQgFgEgIgDQgHgCgIAAIgSAAg");
	this.shape_5.setTransform(-18,-1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AATAxIgZgsIgOAAIAAAsIgOAAIAAhiIAgAAQAGAAAGACQAHACAEACQAFADADAGQADAFAAAIQAAALgHAGQgDAEgFABIgJADIAbAtgAgUgFIAQAAIAIgBIAHgDQADgCACgDQACgDAAgEQAAgEgCgDIgFgGQgDgCgEAAIgHgBIgRAAg");
	this.shape_6.setTransform(-27.4,-1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgKAzIgKgDQgJgEgIgGQgGgIgEgJQgEgKgBgLQABgLAEgKQAEgJAGgHQAIgGAJgFIAKgCIAKgBQALAAAKADIAJAFIAHAGQAHAHAFAJQADAKAAALQAAALgDAKQgFAJgHAIIgHAGIgJAEQgKAEgLAAIgKgBgAgOgkQgHADgGAGQgEAFgDAHQgCAIgBAHQABAIACAIQADAGAEAGQAGAGAHADQAGACAIAAQAIAAAHgCQAIgDAEgGQAFgGADgGQACgIAAgIQAAgHgCgIQgDgHgFgFQgEgGgIgDQgHgDgIAAQgIAAgGADg");
	this.shape_7.setTransform(-38,-1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ordernowcta, new cjs.Rectangle(-53.5,-11.8,107.1,21.2), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.logokale = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(130.4,59.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgVgDgGgEQgKgFAAgNQAAgKAFgHQAHgHAIAAIARAAQAKAAAFgLQACgKABgXIAAl5QgBgXgCgKQgFgLgKAAIgRAAQgIAAgHgHQgFgHAAgKQAAgNAKgFQAGgEAVgDQBdgNBrAAQBOAAA2ASQA0ASAnAoQAlAlAUA5QAUA4AABEQAABNgZA9QgaA+guAlQglAegxAOQgwAOhFAAQhrAAhdgNgAgwjrQgcAFgJALQgKAMAAAhIAAFjQAAAhAUALQAOAHAnADQBMAEAthAQAqg/AAhwQAAhwgqg/Qgrg/hKAAIgeADg");
	this.shape_1.setTransform(62.2,30.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(81.2,88.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(52.4,88.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(22.6,88.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAuBeIgfgyQgGgJgKAAIgtAAQgDAAgEADQgEAEABADIAAAyQAAAGgKACIgPAAQgMAAAAgMIAAi5QgBgIAKAAIBqAAQAgAAAUATQAVATAAAfQAAAYgPAPQgIAJgPAKQgHAGADAGIAjAyQAFAIgFADQgEAFgPAAQgQAAgHgJgAg4g4IAAAuQAAAFAEADQAEACAFAAIA+AAQAQAAALgIQALgIAAgRQAAgQgLgJQgLgJgQABIg+AAQgNAAAAAKg");
	this.shape_5.setTransform(-11.1,88.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAAAABgBQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-44.3,88.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBkQgFgDAAgEIgOhsQgCgGgFAAQgDAAgDADIgxA+QgEAGgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBoQgCALgTAAQgGAAgFgDQgGgDAAgFIAViwQACgJADgEQAEgEALAAQAKAAAFAJIA4BPQAFAHAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAIIAVC1QABALgXAAQgFAAgFgDg");
	this.shape_7.setTransform(-78.1,88.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(14.6,-54.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDwQhFg1gYheIgBgCQgCgMgHAAQgGAAgCALIgBACQgYBfhGA1QhIA3hoAAQh+AAhMhQQhMhQAAiFQAAiHBMhRQBLhQCAAAQBpAABHA3QBHA2AXBgQACALAGAAQAHgBACgKIABgBQAXhgBGg1QBHg3BoAAQB/AABNBQQBMBPAACFQAACHhMBRQhNBRiBAAQhmAAhHg3gACniqQgpA/AABuQAABrApA/QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/gAmFiqQgoA/AABuQAABsAoA+QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/g");
	this.shape_9.setTransform(-21,30.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-98.4,30.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIIAJgFQAEgCAFAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(110.1,30.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAHQgNAJgQAAQgTAAgKgJQgLgJgJgYIimm+QgKgagHgHQgHgHgUgFQgOgCgFgFQgFgFAAgLQAAgVAdgBICvAAQAcAAAAAYQAAAKgHAFQgHAFgRABQgOACgGAFQgGAFAAAJQAAAJADAKIBzFHQACAGAFgBQAEAAACgGIA/i2QAIgYgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgDgGgGQgFgEAAgKQAAgaAdAAICnAAQAdAAAAAYQAAASgcAEQgRACgFAFQgGAFAAAMQAAAKAIAZIBfEsQACAFAEAAQAFAAABgGIBdk6QAEgLAAgJQAAgSgdgEQgbgCAAgVQAAgNAHgGQAIgFARgBIElAAQAVABAIAFQAIAFAAAOQAAAKgGAIQgGAGgJAAIgQAAQgLAAgFALQgCAIAAAZIAABtQAAAeAFAGQAGAHAXAAIB0AAQAXAAAHgIQADgDAAgHIABgdIAAhpQAAgbgDgGQgFgLgKAAIgQAAQgKAAgHgGQgGgIAAgKQAAgOAIgFQAJgFAWgBICaAAQAWABAJAFQAJAFAAAOQAAAKgHAIQgGAGgJAAIgSAAQgEAAgEADQgFADgBAFQgDAJAAAYIAAF9QAAAXADAKQABAFAFACQAEADAEABIASAAQAJAAAGAGQAHAIAAAJQAAAOgJAFQgIAGgXAAIiaAAQgWAAgIgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIAQAAQAKAAAFgLQADgGAAgbIAAh8IgBgeQAAgHgDgEQgHgHgXAAIh0AAQgXAAgGAGQgFAHAAAdIAACCQAAAYACAJQAFALALAAIAQAAQAJAAAGAGQAGAIAAAKQAAAOgIAEQgIAGgVAAIiaAAQgWAAgJgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIARAAQAEgBAFgDQAEgCABgFQADgGAAgbIAAl9QAAgwgkAEQgLABgHAKQgIAIgGAWIiHGzQgJAfgKALQgLALgTAAQgTAAgLgJg");
	this.shape_12.setTransform(-74.6,-36.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgFAAgOQAAgKAGgHQAGgGAJAAIARAAQAEAAAEgDQAEgEACgEQADgIAAgXIAAl/QAAgZgDgJQgDgLgLABIgRAAQgKgBgGgGQgHgHAAgLQAAgNAJgGQAJgFAWAAICcAAQAWAAAJAFQAJAGAAANQAAALgGAHQgHAGgJABIgSAAQgOgBgDALQgDAGAAAcIAAFjQAAAdACAJQACAJAIAFQAGAEALACQALACAagBIAwAAQAvAAAPgfIAIgPQAIgQAPgBQAMAAAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(69.2,-37.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgDALgHAFQgHAFgOAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(114.4,-37.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZNQk7iFjyjyQjyjziFk6QiJlFAAljQAAlkCJlFQCFk6DyjzQDzjyE6iFQFFiJFjAAQFkAAFFCJQE6CFDyDyQDyDzCGE6QCJFFAAFkQAAFjiJFFQiGE6jyDzQjyDyk6CFQlFCJlkAAQljAAlFiJg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-175,-175,350,350);


(lib.interstitialholidaymainsstuffing = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialstuffing();
	this.instance.parent = this;
	this.instance.setTransform(-52,-46.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.interstitialholidaymainsstuffing, new cjs.Rectangle(-52,-46.5,104,93), null);


(lib.holidaymainstable = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialholidaymainstable();
	this.instance.parent = this;
	this.instance.setTransform(-160,-240);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainstable, new cjs.Rectangle(-160,-240,320,480), null);


(lib.holidaymainspotatoes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialholidaymainspotatoes();
	this.instance.parent = this;
	this.instance.setTransform(-70,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainspotatoes, new cjs.Rectangle(-70,-100,140,200), null);


(lib.holidaymainscranberries = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialholidaymainscrannberries();
	this.instance.parent = this;
	this.instance.setTransform(-71.5,-46);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainscranberries, new cjs.Rectangle(-71.5,-46,143,92), null);


(lib.holidaymainscinnamonbuns = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialcinnamonbuns();
	this.instance.parent = this;
	this.instance.setTransform(-80.5,-54.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainscinnamonbuns, new cjs.Rectangle(-80.5,-54.5,161,109), null);


(lib.holidaymainsbrusselsprouts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialholidaymainsbrusselsprouts();
	this.instance.parent = this;
	this.instance.setTransform(-55.5,-95);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainsbrusselsprouts, new cjs.Rectangle(-55.5,-95,111,190), null);


(lib.holidaymainsapples = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialapples();
	this.instance.parent = this;
	this.instance.setTransform(-74,-31);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainsapples, new cjs.Rectangle(-74,-31,148,62), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("EgYsgkQMAxZAAAMAAABIhMgxZAAAg");
	this.shape.setTransform(0,0,1.009,1.032);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-160.5,-240.5,321,481), null);


(lib.ctavideorectangledorange = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("ApmCRIAAkhITNAAIAAEhg");
	this.shape.setTransform(0,0,1.086,1.182);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctavideorectangledorange, new cjs.Rectangle(-66.8,-17.1,133.6,34.3), null);


(lib.ctarectangleorange = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AqbCoIAAlOIU3AAIAAFOg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangleorange, new cjs.Rectangle(-66.7,-16.7,133.6,33.5), null);


(lib.ctarectangledorange = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(12));

	// Layer 1
	this.instance = new lib.ctavideorectangledorange();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(13));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-66.8,-17.1,133.6,34.3);


// stage content:
(lib.interstitialholidaymains = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_61 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_255 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(61).call(this.frame_61).wait(194).call(this.frame_255).wait(2));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(160.4,240.1,1.553,0.731,0,0,0,0.2,0.1);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(257));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(160,240);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(257));

	// fade-from-white
	this.instance_1 = new lib.whiterectanglefade();
	this.instance_1.parent = this;
	this.instance_1.setTransform(172.5,253.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},9).wait(248));

	// logo
	this.instance_2 = new lib.logokale("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(160,37,0.269,0.269,0,0,0,0,0.2);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({regY:0,scaleX:0.05,scaleY:0.05},0).to({regX:0.1,regY:0.1,scaleX:0.29,scaleY:0.29,y:37.1,alpha:1},6).to({regX:0,regY:0.2,scaleX:0.27,scaleY:0.27},8).wait(234));

	// well-make-the-feast
	this.instance_3 = new lib.wellmakethefeast();
	this.instance_3.parent = this;
	this.instance_3.setTransform(160,171.4);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(224).to({alpha:1},13).wait(20));

	// you-take-the-credit
	this.instance_4 = new lib.youtakethecredit();
	this.instance_4.parent = this;
	this.instance_4.setTransform(160,250.5);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(243).to({alpha:1},10).wait(4));

	// well-make
	this.instance_5 = new lib.wellmakeuse();
	this.instance_5.parent = this;
	this.instance_5.setTransform(160,186.3);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(41).to({alpha:1},10).wait(156).to({alpha:0},5).wait(45));

	// the-turkey
	this.instance_6 = new lib.theturkeyuse();
	this.instance_6.parent = this;
	this.instance_6.setTransform(160,215.1);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(48).to({alpha:1},10).wait(29).to({alpha:0},5).wait(165));

	// the-desserts
	this.instance_7 = new lib.thedessertsuse();
	this.instance_7.parent = this;
	this.instance_7.setTransform(160,215.1);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(167).to({alpha:1},10).wait(30).to({alpha:0},5).wait(45));

	// the-sides
	this.instance_8 = new lib.thesidesuse();
	this.instance_8.parent = this;
	this.instance_8.setTransform(160,215.1);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(127).to({alpha:1},10).wait(30).to({alpha:0},5).wait(85));

	// the-stuffing
	this.instance_9 = new lib.thestuffinguse();
	this.instance_9.parent = this;
	this.instance_9.setTransform(160,215.1);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(87).to({alpha:1},10).wait(30).to({alpha:0},5).wait(125));

	// order-now
	this.instance_10 = new lib.ordernowcta();
	this.instance_10.parent = this;
	this.instance_10.setTransform(160,319.4);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(58).to({alpha:1},10).wait(189));

	// cta-rollover
	this.cta_rollover = new lib.ctarectangledorange();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(160.1,318);
	this.cta_rollover.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(58).to({alpha:1},10).wait(189));

	// cta-rectangle
	this.instance_11 = new lib.ctarectangleorange();
	this.instance_11.parent = this;
	this.instance_11.setTransform(160,318,1,1.022);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(58).to({alpha:1},10).wait(189));

	// stuffing
	this.instance_12 = new lib.interstitialholidaymainsstuffing();
	this.instance_12.parent = this;
	this.instance_12.setTransform(52,46.5);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(9).to({alpha:1},10).wait(238));

	// cinnamon-buns
	this.instance_13 = new lib.holidaymainscinnamonbuns();
	this.instance_13.parent = this;
	this.instance_13.setTransform(239.5,54.5);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(14).to({alpha:1},10).wait(233));

	// brussel-sprouts
	this.instance_14 = new lib.holidaymainsbrusselsprouts();
	this.instance_14.parent = this;
	this.instance_14.setTransform(55.5,385);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(19).to({alpha:1},10).wait(228));

	// cranberries
	this.instance_15 = new lib.holidaymainscranberries();
	this.instance_15.parent = this;
	this.instance_15.setTransform(131.5,434);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(24).to({alpha:1},10).wait(223));

	// apples
	this.instance_16 = new lib.holidaymainsapples();
	this.instance_16.parent = this;
	this.instance_16.setTransform(246,449);
	this.instance_16.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(29).to({alpha:1},10).wait(218));

	// potatoes
	this.instance_17 = new lib.holidaymainspotatoes();
	this.instance_17.parent = this;
	this.instance_17.setTransform(250,357);
	this.instance_17.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(34).to({alpha:1},10).wait(213));

	// table
	this.instance_18 = new lib.holidaymainstable();
	this.instance_18.parent = this;
	this.instance_18.setTransform(160,240);

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(257));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(135.1,221.1,395,545);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 320,
	height: 480,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;