(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[251,505,148,62],[322,394,161,109],[322,202,111,190],[0,482,143,92],[322,0,140,200],[0,0,320,480],[145,482,104,93]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.interstitialapples = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.interstitialcinnamonbuns = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.interstitialholidaymainsbrusselsprouts = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.interstitialholidaymainscrannberries = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.interstitialholidaymainspotatoes = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.interstitialholidaymainstable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.interstitialstuffing = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.youtake = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AhNBaQgigjAAg0QAAg3AjgjQAjglA1ABQAugBAcAbQAaAaAAAtQAAAPgEAEQgEAFgSAAIhbAAQgIAAgEgEQgFgEAAgGQAAgHAFgDQAEgDAIgBIAxAAIAMgCQADgBAAgGQAAgWgPgQQgQgQgVAAQgdAAgOAZQgOAYAAAkQAAAkAUAcQATAbAdAAQASgBAMgDQAMgEAMgIIAIgHQAMgKAHAAQAFAAAEAEQADADAAAFQAAAFgGAJQgGAIgKAJQgVAQgTAJQgTAGgXAAQgyABgigjg");
	this.shape.setTransform(91.3,5.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("ABOCvIgKgCQgLgEgXgdIgJgNIgFgFQg6hLgEAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBABAAAAIgBAKIAAALIACAyQABAOAEAEIANAHQALAFAAAJQAAAJgMAEQgMAEgfAAQgkAAgMgEQgLgEAAgLQAAgIALgEIAGgDQAHgDADgMQACgMAAgbIAAgeIAAglIAAgdIgChZQgBgWgEgEQgCgDgMgDIgHgCIgJgFIgCgGQAAgGAEgEQAFgEARgGIAggJIAZgEQAHAAADAFQADAEAAAMIgBAuIgCA+IAAA7IABAMQAAAAABABQAAABABAAQAAAAABABQAAAAABAAIAKgGIARgOIAXgXQAGgHAAgDQAAgDgJgEQgIgFAAgHQAAgLAMgEQAMgFAjAAQAWAAALAFQAKAEAAAJQAAAMgRAEQgSAEgHAFQgIAFgVATIgEAEIgIAJIgCAFQAAAEAVAcIACADIApAyQARAUAJAHQAGAEAQAFQAPAFAAAJQAAALgLAEQgLAFgaAAg");
	this.shape_1.setTransform(66.2,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AArBwIgNgMIgKAFQgeAUgdAAQgjAAgWgUQgVgVAAghQAAgmAcgUQAbgWAyAAQAMAAAGAEQAGADAAAJQAAAOgQAAQgYAAgOALQgPAMAAAUQAAATANALQAMAMAWAAQAWAAAKgKQAKgLAAgZIAAhaQAAgVgJgLQgJgMgQAAQgMAAgKAGQgKAFgKAKIgFAHQgOASgQAAQgKAAgFgGQgGgGAAgLQAAgWAcgPQAbgQAsAAQAaAAATAHQATAHAKANQAHAKADAOQADAPAAAiIAABMQAAAOADAHQACAGAFACIAHACQAPAEAAAIQAAALgQAKQgQAJgVAAQgLAAgLgNg");
	this.shape_2.setTransform(39.5,5.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AgyCqQgNgEAAgLQAAgJANgFQANgFACgEQADgEABgnIAChxIgBg/IgCgmQgBgGgEgCQgEgCgKAAIgKAAQgRAAgJADQgJAEgHAKIgHAQIgHAQIgHAHQgEADgFAAQgHAAgDgGQgDgGAAgPQAAggAHgTQAIgTALAAIADAAQATADAcAAICMAAQAdAAAUgDIACAAQAMAAAHATQAHATAAAgQAAAOgDAHQgDAGgIAAIgIgDIgHgHIgHgQIgHgQQgHgKgJgEQgKgDgQAAIgKAAQgKAAgEACQgEACgBAGIgCAnIgBA+IACBxQABAnADAEQACAEANAFQANAFAAAJQAAALgNAEQgOAEglAAQgkAAgOgEg");
	this.shape_3.setTransform(10.9,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AA0B5QgDgDAAgIIAAgRIgBgBIgBgBQgDAAgFAGIgDAEQgMALgOAGQgOAGgRAAQgSAAgQgHQgQgHgKgMQgMgOgEgTQgFgTAAgyIAAgRIAAgRIAAgFQAAgUgCgFQgDgGgJgDIgJgDQgOgDAAgJQAAgGAFgEQAFgEARgGIAggIIAZgEQAHAAADAFQADAFAAAKIgBAKIgCBZQAAAwAKATQAKASAYAAQAbAAAMgYQAMgYAAg6IAAgSQAAgTgDgFQgDgGgIgDIgKgDQgNgDAAgJQAAgGAFgEQAEgEARgGIAggIIAZgEQAHAAADAFQADAEAAALIAAAOIgDBhIAAApIACAQQACAJAMAFIAAAAIAEACQAOAEAAAIQAAAGgEAEQgFAEgKAEIgiALQgQAEgJAAQgHAAgDgEg");
	this.shape_4.setTransform(-32.3,5.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AhWBaQgigkAAg1QAAg1AkgkQAjgjA1AAQA0AAAhAhQAgAhAAA1QAAA3gjAkQgjAlg0AAQgzAAgigigAgthGQgOASAAAhQAAAuAUAgQAUAgAcAAQAXAAAPgTQAOgVAAgfQAAgvgUgfQgUgggcAAQgXAAgPAUg");
	this.shape_5.setTransform(-59.7,5.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgxCoQgOgEgBgKQABgKAPgGIAKgFQAIgGABhiIAAgVIgcgvIgthHQgOgUgJgFIgLgFQgQgFAAgJQAAgKALgEQAMgEAuABQAugBALAEQALAEAAAKQAAAJgSAGIgCABIgHAFIgCAHQAAAFAKARIAwBKIApg9QANgXAAgGQAAgGgEgFQgDgEgLgEQgJgDgDgDQgDgEAAgFQAAgKAJgEQALgEAnABQAmgBAKAEQALAEAAAKQAAAJgNAFIgSAJQgLAJgXAiQgXAjgiA7IAAAqQABBQAGAFIALAFQAPAFAAALQAAAKgNAEQgNAEgmAAQgkAAgNgEg");
	this.shape_6.setTransform(-88.5,0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.youtake, new cjs.Rectangle(-105.9,-30.4,211.9,60.8), null);


(lib.whiterectanglefade = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ege2AqlMAAAhVJMA9tAAAMAAABVJg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.whiterectanglefade, new cjs.Rectangle(-197.4,-272.4,395,545), null);


(lib.wellmake = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AhNBaQgigjAAg0QAAg3AjgjQAjglA1ABQAugBAcAbQAaAaAAAtQAAAPgEAEQgEAFgSAAIhbAAQgIAAgEgEQgFgEAAgGQAAgHAFgDQAEgDAIgBIAxAAIAMgCQADgBAAgGQAAgWgPgQQgQgQgVAAQgdAAgOAZQgOAYAAAkQAAAkAUAcQATAbAdAAQASgBAMgDQAMgEAMgIIAIgHQAMgKAHAAQAFAAAEAEQADADAAAFQAAAFgGAJQgGAIgKAJQgVAQgTAJQgTAGgXAAQgyABgigjg");
	this.shape.setTransform(109.1,5.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("ABOCvIgKgCQgLgEgXgdIgJgNIgFgFQg6hLgEAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBABAAAAIgBAKIAAALIACAyQABAOAEAEIANAHQALAFAAAJQAAAJgMAEQgMAEgfAAQgkAAgMgEQgLgEAAgLQAAgIALgEIAGgDQAHgDADgMQACgMAAgbIAAgeIAAglIAAgdIgChZQgBgWgEgEQgCgDgMgDIgHgCIgJgFIgCgGQAAgGAEgEQAFgEARgGIAggJIAZgEQAHAAADAFQADAEAAAMIgBAuIgCA+IAAA7IABAMQAAAAABABQAAABABAAQAAAAABABQAAAAABAAIAKgGIARgOIAXgXQAGgHAAgDQAAgDgJgEQgIgFAAgHQAAgLAMgEQAMgFAjAAQAWAAALAFQAKAEAAAJQAAAMgRAEQgSAEgHAFQgIAFgVATIgEAEIgIAJIgCAFQAAAEAVAcIACADIApAyQARAUAJAHQAGAEAQAFQAPAFAAAJQAAALgLAEQgLAFgaAAg");
	this.shape_1.setTransform(84,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AArBwIgNgMIgKAFQgeAUgdAAQgjAAgWgUQgVgVAAghQAAgmAcgUQAbgWAyAAQAMAAAGAEQAGADAAAJQAAAOgQAAQgYAAgOALQgPAMAAAUQAAATANALQAMAMAWAAQAWAAAKgKQAKgLAAgZIAAhaQAAgVgJgLQgJgMgQAAQgMAAgKAGQgKAFgKAKIgFAHQgOASgQAAQgKAAgFgGQgGgGAAgLQAAgWAcgPQAbgQAsAAQAaAAATAHQATAHAKANQAHAKADAOQADAPAAAiIAABMQAAAOADAHQACAGAFACIAHACQAPAEAAAIQAAALgQAKQgQAJgVAAQgLAAgLgNg");
	this.shape_2.setTransform(57.3,5.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("ABZCoQgNgEAAgKQAAgKAPgGIAKgFQAFgEABgKQACgKAAghIAAgMIAAhlIgBg8IgeBPQhGC2gQAAQgHABgOgaQgOgZgihNIg0h5IgCBfIgBBAIACAsQABALAEADIALAFQAOAFAAALQAAAKgMAEQgMAEgdAAQgaABgMgGQgMgEAAgKQAAgIANgHQANgFABgFQAEgMADg9QAEg9AAhLIAAgIQAAgagCgIQgCgIgGgDIgLgGQgQgFAAgKQAAgKALgDQALgEAjABIAiAAIAJACQAFADARArIANAiIAHARQA6CPAEAAQAGAAAVg0QAWgyAdhUIAFgPQAIgaAIgIQADgEAKgCIAhgBQAggBAKAEQALADAAAKQAAAKgOAFIgGACQgHAFgDAJQgCAJAAAlIACCIQADA9ACAJQABAFALAEIAFACIAJAGQADADAAAGQAAAKgNAEQgOAEgnAAQgkAAgNgEg");
	this.shape_3.setTransform(22.6,0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AgoCsQgLgEAAgLQAAgHAJgFIANgGQAEgEACgPIABgvIAAglIAAgtIAAgSQAAg8gCgRQgCgSgFgDIgPgFQgPgEAAgIQAAgGAEgEQAFgEARgGIAggJIAYgEQAHAAADAFQADAEAAAMIAAASQgDBVAABWIABBRQACASAEAEIANAHQALAFAAAJQAAAJgMAEQgMAEgfAAQgjAAgMgEg");
	this.shape_4.setTransform(-19.3,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AgoCsQgLgEAAgLQAAgHAJgFIANgGQAEgEACgPIABgvIAAglIAAgtIAAgSQAAg8gCgRQgCgSgFgDIgPgFQgPgEAAgIQAAgGAEgEQAFgEARgGIAggJIAYgEQAHAAADAFQADAEAAAMIAAASQgDBVAABWIABBRQACASAEAEIANAHQALAFAAAJQAAAJgMAEQgMAEgfAAQgjAAgMgEg");
	this.shape_5.setTransform(-32.7,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgEBGIgRhpIAAgDIAAgGQAAgMAGgGQAFgHAKAAQAKAAAGAHQAGAGAAAMIAAAGIgBADIgRBpg");
	this.shape_6.setTransform(-43.1,-9.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AhNBaQgigjAAg0QAAg3AjgjQAjglA1ABQAugBAcAbQAaAaAAAtQAAAPgEAEQgEAFgSAAIhbAAQgIAAgEgEQgFgEAAgGQAAgHAFgDQAEgDAIgBIAxAAIAMgCQADgBAAgGQAAgWgPgQQgQgQgVAAQgdAAgOAZQgOAYAAAkQAAAkAUAcQATAbAdAAQASgBAMgDQAMgEAMgIIAIgHQAMgKAHAAQAFAAAEAEQADADAAAFQAAAFgGAJQgGAIgKAJQgVAQgTAJQgTAGgXAAQgyABgigjg");
	this.shape_7.setTransform(-59.8,5.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AAhBTIgziEQgPgrgKgUQgKgUgIgHIgOgFQgMgFAAgJQAAgKALgDQALgEAuAAQAsAAALAEQALADAAAKQAAAKgSAGIgCABQgFACgDADQgDAEAAAFQAAAJAMAgIAnBoIARAnQAFAKAEAAQADAAAFgIIAQgjIAEgKQAxh3AAgOQAAgIgDgFQgEgFgIgDIgFgDQgOgGAAgJQAAgKAJgDQAKgEAnAAQAmAAAKAEQAKADAAAKQAAAJgOAGIgLAFQgQALggBSIgUAxIgtBwIgJAWQgOAmgLAAQgMAAgjhdgAhiCcIgDgIQgfhCgvh6IgVg6IgPgdQgGgJgHgFIgHgCQgQgFAAgKQAAgKAMgDQALgEAtAAQAtAAALAEQALADAAAKQAAAKgSAGIgCABQgGACgCAEQgDADAAAFQAAAIAKAdIAoBpIATArQAEAJAEAAQAEAAAFgMIAMgbQAFgQANAAQAPAAAAAQIgDAPIgfBMIgHASQgPAngJAAQgJAAgIgUg");
	this.shape_8.setTransform(-97,0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wellmake, new cjs.Rectangle(-123.7,-30.4,247.5,60.8), null);


(lib.wellmakethefeast = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgHAIQgEgDABgFQgBgEAEgDQADgEAEAAQAFAAADAEQADADAAAEQAAAFgDADQgDAEgFAAQgEAAgDgEg");
	this.shape.setTransform(104,4.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AgBA8IgGgBQgDgBAAgDIAAhYQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBIgFgBIgJAAIgJAAIgGAAQgDAAgBgCIgCgGIAAgEIABgEIACgEIADAAIBTAAQADgBACADIABAGIAAADIgBAFIgCADIgEABIgXAAQgDAAgCABQgCACAAAEIAABXIgBADIgEACIgEAAg");
	this.shape_1.setTransform(96.5,-0.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AgaA6QgNgFgKgJIgBgCIgBgDIACgEIAEgEIAEgDIAEgBQACAAADACIAJAFIAJAFQAHADAHAAIAJgBQAFgBAEgCQAFgCADgDQACgEAAgFQAAgFgDgDQgEgDgFgCIgNgCIgMgCIgOgDQgHgCgGgDQgGgDgDgGQgDgGAAgJQAAgKAFgHQAFgGAGgFQAIgEAJgCQAJgDAHAAIALABIAMADQAGACAGADQAFADAEAEIABACIABACQAAAAgBABQAAABAAAAQAAABAAAAQgBABAAAAIgEAEIgEADIgFABIgDgBQgHgFgHgEQgHgDgIAAIgIABIgIADQgEACgDADQgCADAAAFQAAAGAGADQAFADAJABIASADQAKABAIADQAJAEAGAFQAFAHAAANQAAAKgEAHQgFAIgIAFQgIAFgJACQgKADgHAAQgNAAgNgFg");
	this.shape_2.setTransform(85.7,-0.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AAwA9IgEAAIgGgBQgEgBgBgDIgHgQIgCgCQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgoAAIgBABIgCABIgCABIgBABIgHAQIgCADIgDABIgEAAIgDABIgDAAIgEgBIgDgBQgBAAAAgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAyhwQAAgBAAAAQABgBAAAAQAAAAABAAQAAgBABAAIADgBIAFABQABAAABABQAAAAABAAQAAAAABABQAAAAAAABIAwBwIAAABQAAAAAAABQAAAAgBAAQAAABAAAAQAAABgBAAIgDABgAAAgSIgBACIgCADIgCAGIgDAGIgDAGIgCAGIgBACIABADIACABIAXAAIADgBIABgDIgCgFIgEgJIgEgKIgDgGIgDgBg");
	this.shape_3.setTransform(74.1,-0.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AgoA8IgEgBQAAgBgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhuQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAIAEgBIBTAAIADACIABAEIAAAEIAAAEIgBAEQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAIg+AAIgDACIgCADIAAARQAAAAAAABQAAAAABABQAAAAAAABQAAAAABABIAEABIAnAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIABAEIABAFIAAACQAAAFgFACIgnAAQAAAAgBAAQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAgBABQAAAAAAABQAAAAgBABQAAABAAAAIAAASQAAABAAABQAAAAABABQAAAAAAABQAAAAABAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIA9AAQAEACAAAFIAAADIgBAFIgBAEQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_4.setTransform(63,-0.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AgjA9IgEAAQgFAAgCgEIAAhvQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBABgBIAEgBIBSAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAIACADIABAFIAAACQAAAEgBADQgBACgDABIg8AAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABIAAAPQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAABABQAAAAABAAQAAAAABAAIAmAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAIACAFIAAAEIAAADIgBAEQAAABAAABQgBAAAAAAQgBABAAAAQgBAAAAAAIgnAAIgCABIgCABIgBACIgBACIAAArIgDACIgEACg");
	this.shape_5.setTransform(52.4,-0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgoA8IgEgBQAAgBgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhuQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAIAEgBIBTAAIADACIABAEIAAAEIAAAEIgBAEQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAIg+AAIgDACIgCADIAAARQAAAAAAABQAAAAABABQAAAAAAABQAAAAABABIAEABIAnAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIABAEIABAFIAAACQAAAFgFACIgnAAQAAAAgBAAQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAgBABQAAAAAAABQAAAAgBABQAAABAAAAIAAASQAAABAAABQAAAAABABQAAAAAAABQAAAAABAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIA9AAQAEACAAAFIAAADIgBAFIgBAEQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_6.setTransform(35.7,-0.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AAlA+IgFgBIgFgDIAAgrQAAAAAAgBQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAgBgBAAQAAgBgBAAQAAAAgBAAQgBAAAAAAIgoAAQgDAAgCACQgCADAAACIAAAqQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgEABIgEAAIgFAAIgEgCQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAgBgBIAAhxIADgDIAEgBIAFgBIAEAAQAEAAADAFIAAAmQAAABAAAAQAAABAAABQAAAAABABQAAAAAAABQABAAAAABQABAAAAAAQABABAAAAQABAAAAAAIApAAQADAAACgCQABgBAAAAQAAgBABAAQAAgBAAAAQAAgBAAgBIAAgmQADgEADAAIAIAAIAFAAIAEAEIgBBxQgBAEgEABg");
	this.shape_7.setTransform(22.9,-0.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AgBA8IgGgBQgDgBAAgDIAAhYQAAgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBIgFgBIgKAAIgJAAIgEAAQgEAAgBgCIgCgGIAAgEIABgEIACgEIAEAAIBSAAQAEgBABADIABAGIAAADIgBAFIgCADIgEABIgXAAQgDAAgCABQgCACAAAEIAABXIgBADIgEACIgEAAg");
	this.shape_8.setTransform(11.3,-0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AgoA8IgEgBQAAgBgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhuQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBABAAIAEgBIBTAAIADACIABAEIAAAEIAAAEIgBAEQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAIg+AAIgDACIgCADIAAARQAAAAAAABQAAAAABABQAAAAAAABQAAAAABABIAEABIAnAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIABAEIABAFIAAACQAAAFgFACIgnAAQAAAAgBAAQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAgBABQAAAAAAABQAAAAgBABQAAABAAAAIAAASQAAABAAABQAAAAABABQAAAAAAABQAAAAABAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIA9AAQAEACAAAFIAAADIgBAFIgBAEQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_9.setTransform(-4,-0.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AAcA+IgFgDIgdgtIgEgDIgFgBQgDAAgDACQgEABABAEIAAAlQAAABgBAAQAAABAAAAQAAABAAAAQgBABAAAAIgFACIgEABIgFAAQgHAAAAgGIAAhwIAEgDIADgBIAEgBIAEABQAGAAACAEIAAAlQgBADADACIAFABQACAAADgDIAhgoIACgBIADgBIAEABIAEADIAEADQAAAAABABQAAAAAAAAQABABAAAAQAAAAAAABIgBADIgdAiIgCADIgBADIABADIABADIAmAzIABACIAAABQAAABgBAAQAAABAAAAQAAABAAAAQgBAAAAABIgEACIgFACIgEABg");
	this.shape_10.setTransform(-15.6,-0.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AAwA9IgEAAIgGgBQgEgBgBgDIgHgQIgCgCQAAgBgBAAQAAAAAAAAQgBgBAAAAQgBAAAAAAIgoAAIgBABIgCABIgCABIgBABIgHAQIgCADIgDABIgEAAIgDABIgDAAIgEgBIgDgBQgBAAAAgBQAAAAAAAAQgBAAAAgBQAAAAAAgBIAyhwQAAgBAAAAQABgBAAAAQAAAAABAAQAAgBABAAIADgBIAFABQABAAABABQAAAAABAAQAAAAABABQAAAAAAABIAwBwIAAABQAAAAAAABQAAAAgBAAQAAABAAAAQAAABgBAAIgDABgAAAgSIgBACIgCADIgCAGIgDAGIgDAGIgCAGIgBACIABADIACABIAXAAIADgBIABgDIgCgFIgEgJIgEgKIgDgGIgDgBg");
	this.shape_11.setTransform(-27.9,-0.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006F46").s().p("AAoA9IgFgBQgDgCAAgDIAAg3QAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBgBAAIgCgBQgBAAAAAAQgBAAAAAAQgBAAAAABQAAAAgBABIgTAeQgCADgDABIgEgBIgCgDIgRgeQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAAAIgDACIgBABIAAA1QgCAFgDABIgIABIgDgBIgDgBIgCgCIgBgDIAAhsQABgEADgBIAHAAIAEABIAEADIAcAvQACAEAEAAIADgBIADgDIAcgvQADgFAGAAIAGABQAAAAABAAQAAABABAAQAAABAAAAQABABAAABIAABtIgBAEIgEACIgEABg");
	this.shape_12.setTransform(-40.4,-0.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006F46").s().p("AgpA9QAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBgBIgBgDIAAhuQAAAAAAgBQAAAAAAgBQABgBAAAAQAAAAAAgBIAEgCIAEAAIAEAAQADAAADABQACABACAEIAABUIAAAEIACADQADADAFAAIA2AAIADABIACAEIABADIAAAEIgBAHQgBACgFAAg");
	this.shape_13.setTransform(-57.3,-0.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006F46").s().p("AgpA9QAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBIgCgDIAAhuQAAAAAAgBQAAAAAAgBQABgBAAAAQAAAAABgBIADgCIAEAAIAEAAQAEAAACABQACABABAEIAABUIABAEIACADQADADAEAAIA2AAIAEABIACAEIABADIAAAEIgBAHQgCACgEAAg");
	this.shape_14.setTransform(-68.6,-0.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006F46").s().p("AgEAQIgEgBIgBgDIAAgXQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAABAAIAEgBIAEAAIADAAIADABIACADIAAAMIgBAFIgDAEIgEADIgFADIgBAAIAAAAg");
	this.shape_15.setTransform(-76.9,-4.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006F46").s().p("AgoA8IgEgBQAAgBgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhuQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBABAAIAEgBIBTAAIADACIABAEIAAAEIAAAEIgBAEQAAAAAAABQgBAAAAAAQgBABAAAAQgBABAAAAIg+AAIgDACIgCADIAAARQAAAAAAABQAAAAABABQAAAAAAABQAAAAABABIAEABIAnAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIABAEIABAFIAAACQAAAFgFACIgnAAQAAAAgBAAQAAAAgBAAQAAAAgBABQAAAAgBABQAAAAgBABQAAAAAAABQgBAAAAABQAAABAAAAIAAASQAAABAAABQAAAAABABQAAAAAAABQAAAAABAAQAAABABAAQAAAAABAAQAAABABAAQAAAAABAAIA9AAQAEACAAAFIAAADIgBAFIgBAEQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_16.setTransform(-84.3,-0.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006F46").s().p("AAaA9IgBgCIgUgyIgBgDIgEgCIgDADIgCACIgVAxIgBADIgBABQAAAAgBAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIAAgDIgDgHIgGgOIgHgSIgIgTIgHgSIgGgRIgFgMIgCgGIABgDIAEgDIAEgCIAFAAIAEABIADAEIAWA4IACACIACABIAEAAIABgDIASgpIACgCIACgBIADABIACACIASAqIABACIADABIADgBIACgDIAWg5QADgEAEAAIAFAAIAEACIADADQAAAAABAAQAAABAAAAQAAABAAAAQABABAAAAIgCAGIgFAMIgHARIgHASIgIATIgHASIgGAOIgDAIIgBACIgCABg");
	this.shape_17.setTransform(-98.6,-0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wellmakethefeast, new cjs.Rectangle(-108.6,-10.8,217.3,21.6), null);


(lib.theturkey = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgZAaQgLgLAAgPQAAgPALgLQAKgKAPAAQAQAAAKAKQALALAAAPQAAAPgLALQgLALgPAAQgPAAgKgLg");
	this.shape.setTransform(118.7,17.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AhuCeQgMgKAAgPQAAgMAJgIQAIgKANABIAKABIAHAGIAGAJQAHAJAEAAQAMAAANgRQANgSAAgSQgBgVgQgmIgDgFIgmhUIgWgvQgEgIgOgGQgIgDgDgDQgDgEAAgFQAAgKANgFQAMgEAjAAQAjAAAMAEQALAEAAAKIgBAHIgEAEIgJAEQgJAEAAAEIAEASIATAwIAUAtQAGALAEAAQACAAAFgLIAPgmIASgvQAGgRAAgGQAAgHgOgIQgNgHAAgHQAAgHALgEQALgEAbAAQAdAAAKAEQAKAEAAAKQAAAIgOADIgKAEQgNAHgPApIgIATIgeBLQgnBkgYAeQgaAegjAAQgRAAgMgKg");
	this.shape_1.setTransform(100.3,13.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AhNBaQgigjAAg0QAAg2AjglQAjgjA1gBQAuABAcAaQAaAaAAAsQAAAPgEAFQgEAFgSAAIhbAAQgIAAgEgEQgFgEAAgHQAAgGAFgDQAEgEAIABIAxAAIAMgDQADgBAAgFQAAgYgPgPQgQgQgVAAQgdAAgOAZQgOAYAAAkQAAAlAUAaQATAbAdAAQASABAMgEQAMgEAMgIIAIgHQAMgJAHAAQAFAAAEACQADAEAAAFQAAAFgGAJQgGAJgKAHQgVASgTAHQgTAIgXAAQgygBgigig");
	this.shape_2.setTransform(75.6,8.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("ABOCvIgKgCQgLgEgXgdIgJgNIgFgFQg6hLgEAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAABgBAAIgBAKIAAALIACAyQABAOAEAEIANAHQALAFAAAJQAAAJgMAEQgMAEgfAAQgkAAgMgEQgLgEAAgLQAAgIALgEIAGgDQAHgDADgMQACgMAAgbIAAgeIAAglIAAgdIgChZQgBgWgEgEQgCgDgMgDIgHgCIgJgFIgCgGQAAgGAEgEQAFgEARgGIAggJIAZgEQAHAAADAFQADAEAAAMIgBAuIgCA+IAAA7IABAMQABABAAAAQAAABABAAQAAAAABABQAAAAABAAIAKgGIARgOIAXgXQAGgHAAgDQAAgDgJgEQgIgFAAgHQAAgLAMgEQAMgFAjAAQAWAAALAFQAKAEAAAJQAAAMgRAEQgSAEgHAFQgIAFgVATIgEAEIgIAJIgCAFQAAAEAVAcIACADIApAyQARAUAJAHQAGAEAQAFQAPAFAAAJQAAALgLAEQgLAFgaAAg");
	this.shape_3.setTransform(50.5,3.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AhIB3QgMgEABgLQAAgIALgEIAHgDQAFgDADgJQADgHAAgSIgBgQIAAgUIAAgOQAAgsgBgMQgDgOgFgDIgKgEQgPgEAAgJQAAgFAFgEQAEgFAKgEIAhgKIAVgEQALAAAEAgIABAFIABABQANgTANgLQANgJAOgBQAQABAKAJQAKALAAAQQAAARgIAJQgHAKgOAAIgMgDIgJgHIgGgJQgDgGgDAAQgQAAgGAXQgGAWAABJQAAAUACALQADAKAGADIAKADQAOAFAAAKQAAAIgNAFQgNADggAAQglAAgMgDg");
	this.shape_4.setTransform(27.7,8.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AA0B5QgDgDAAgIIAAgRIgBgBIgBgBQgDAAgFAGIgDAEQgMALgOAGQgOAGgRAAQgSAAgQgHQgQgHgKgMQgMgOgEgTQgFgTAAgyIAAgRIAAgRIAAgFQAAgUgCgFQgDgGgJgDIgJgDQgOgDAAgJQAAgGAFgEQAFgEARgGIAggIIAZgEQAHAAADAFQADAFAAAKIgBAKIgCBZQAAAwAKATQAKASAYAAQAbAAAMgYQAMgYAAg6IAAgSQAAgTgDgFQgDgGgIgDIgKgDQgNgDAAgJQAAgGAFgEQAEgEARgGIAggIIAZgEQAHAAADAFQADAEAAALIAAAOIgDBhIAAApIACAQQACAJAMAFIAAAAIAEACQAOAEAAAIQAAAGgEAEQgFAEgKAEIgiALQgQAEgJAAQgHAAgDgEg");
	this.shape_5.setTransform(3.6,8.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgyCqQgNgEAAgLQAAgJANgFQANgFACgEQADgEABgnIAChxIgBg/IgCgmQgBgGgEgCQgEgCgKAAIgKAAQgRAAgJADQgJAEgHAKIgHAQIgHAQIgHAHQgEADgFAAQgHAAgDgGQgDgGAAgPQAAggAHgTQAIgTALAAIADAAQATADAcAAICMAAQAdAAAUgDIACAAQAMAAAHATQAHATAAAgQAAAOgDAHQgDAGgIAAIgIgDIgHgHIgHgQIgHgQQgHgKgJgEQgKgDgQAAIgKAAQgKAAgEACQgEACgBAGIgCAnIgBA+IACBxQABAnADAEQACAEANAFQANAFAAAJQAAALgNAEQgOAEglAAQgkAAgOgEg");
	this.shape_6.setTransform(-26,3.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AhNBaQgigjAAg0QAAg2AjglQAjgjA1gBQAuABAcAaQAaAaAAAsQAAAPgEAFQgEAFgSAAIhbAAQgIAAgEgEQgFgEAAgHQAAgGAFgDQAEgEAIABIAxAAIAMgDQADgBAAgFQAAgYgPgPQgQgQgVAAQgdAAgOAZQgOAYAAAkQAAAlAUAaQATAbAdAAQASABAMgEQAMgEAMgIIAIgHQAMgJAHAAQAFAAAEACQADAEAAAFQAAAFgGAJQgGAJgKAHQgVASgTAHQgTAIgXAAQgygBgigig");
	this.shape_7.setTransform(-67.3,8.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AAhCsQgMgFAAgIQAAgKAMgEIAJgEQAGgDACgKQACgKAAgaQAAhNgKgSQgJgTgagBQgLABgLAHQgNAIgFAMQgGAKgCATQgCASAAAvQAAAYACAHQACAJAFACIAJAEQAMAEAAAKQAAAIgLAFQgMADgfAAQglAAgMgDQgMgEAAgLQAAgIAMgEIAGgDQAHgDACgLQADgKAAgaIAAgnIAAgkIgChsQgBgagDgGQgDgCgOgFQgPgEAAgIQABgGAFgFQAGgEAVgJIAZgGIAVgDQAJAAADAFQADAFAAALIAAAKIgDBeIAAANIACAFIADACIAGgFIAIgKQAMgMANgFQANgHAPAAQApABAUAaQAUAbAAA0IABAXIAAAqIAAAOQAAAMACAGQADAFAFADIAFACQANAFAAAIQAAALgMAEQgMADglAAQgfAAgMgDg");
	this.shape_8.setTransform(-94.5,3.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AgMCQQgMgEgJgIQgIgIgDgNQgEgNAAgkIAAh/IgWAAIgHgCIgCgHIAAgFQAAgIAZgVIAKgJIAKgHQAYgXAJAAIAHACQACACABAEIAAAtIA1AAQAGAAADACQACADAAAGIAAAGQgBAHgCACQgCADgGAAIgyAAIgDACIgBAFIAAB2QgBAfAGAIQAFAIAOgBQAHAAANgDIAQgEQAFAAADADQAEADAAAFQAAANgVANQgTALgbABQgNgBgMgDg");
	this.shape_9.setTransform(-116.7,6.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.theturkey, new cjs.Rectangle(-127.4,-27.3,254.8,60.8), null);


(lib.thestuffing = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgZAaQgLgLAAgPQAAgPALgLQAKgKAPAAQAQAAAKAKQALALAAAPQAAAPgLALQgLALgPAAQgPAAgKgLg");
	this.shape.setTransform(125.6,17.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AhYCcQgegTAAgaQAAgMAGgIQAGgIAOAAQAKAAAFAGQAGAGADALQAFARAQALQAPAKAdAAQAfAAAVgNQAVgMAAgSQAAgMgIgGQgIgGgOAAIgcACIgkACQgrAAgXgOQgXgPAAgTQAAgMAJgMQAIgKARgLQgOgMgHgPQgHgQAAgSQAAgnAdgaQAegaAtAAIAYACIAlAIQAJAAAKgFQALgEAPgLIAHAIIADAIQAAAKgIAJQgHAKgOAHIAHATIADAUQAAAogdAZQgeAXguAAIgZgBIgXgFIgHAJIgCAJQAAALALAFQALAGAYAAIAjgDIAmgDQAhAAASAOQARAOAAAZQAAAmglAZQglAag5AAQguAAgegTgAgmh2QgNAPAAAYQAAAYAMAPQAMAPAUAAQATAAANgPQAOgPAAgYQAAgYgNgPQgNgQgUAAQgTAAgMAQg");
	this.shape_1.setTransform(107.3,12.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("Ah1B3QgMgEAAgLQAAgIAMgFIAGgCQAHgDACgJQADgHAAgSIgBgQIAAgUIAAgXQAAgmgCgMQgCgLgEgDIgMgEQgOgEAAgJQAAgFAEgEQAFgFAKgEIAjgKIAYgFQAHAAADAEQADADAAAIIAAARIAAABIACABIABAAIABgBIAGgFIAFgEQAagYAdgBQARAAAQAIQAQAHALANQALANAFATQAEARAAAnIAAAgIAAAPIAAAOQAAAQACAIQADAGAGAEIAGACQALAFAAAIQAAALgLADQgLAEgkAAQgiAAgLgDQgLgFAAgIQAAgKALgEIAJgEQAGgDACgKQACgLAAgaQAAhLgJgTQgKgTgZgBQgMABgMAHQgLAIgGANQgGAKgCATQgCASAAAvQAAAXACAIQACAIAFACIAJAEQAMAEAAAKQAAAIgMAFQgLADgfAAQglAAgMgDg");
	this.shape_2.setTransform(79.5,8.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AgqCrQgMgEAAgLQAAgIAMgEIAGgDQAHgDACgIQADgIAAgSIgBgQIAAgUIAAgYQAAgmgCgLQgCgLgEgDIgMgEQgOgEAAgIQAAgGAEgEQAFgEAKgEIAkgMIAZgEQAGAAADAEQADAFAAALIAAAOIgBALIgBA8IAAABIgBA7QAAAXACAJQACAKAFACIAJAEQAMAFAAAJQAAAJgMAEQgLAEgfAAQgkAAgMgEgAgdh4QgKgIAAgNQAAgNALgKQAMgKAQAAQAOAAALAJQAKAJAAANQAAANgLAJQgMAJgPAAQgQAAgKgIg");
	this.shape_3.setTransform(58.5,3.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AhDCrQgLgDAAgKQAAgHALgFIAGgCQAGgEACgHQACgIAAgUIAAgXIAAhzIgaAAQgGAAgCgDQgCgCAAgHIAAgFQAAgGACgDQADgDAFAAIAZAAIgCgSIgBgRQAAglAWgUQAWgUAmAAQAbAAARAMQARAMAAATQAAAMgGAFQgGAGgLAAQgIAAgGgDQgGgEgEgGIgFgJQgIgRgOAAQgJAAgFAGQgGAGAAAJIAGAbQAEAVABAQIAjAAQAGAAACADQACACAAAHIAAAFQAAAHgCACQgDADgFAAIgjAAIAAB6QAAAfACAJQACAKAFACIAJAEQAOAEAAAKQAAAJgLAEQgMADgiAAQgjAAgMgEg");
	this.shape_4.setTransform(47.1,3.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AhDCrQgLgDAAgKQAAgHALgFIAGgCQAGgEACgHQACgIAAgUIAAgXIAAhzIgaAAQgGAAgCgDQgCgCAAgHIAAgFQAAgGACgDQADgDAFAAIAZAAIgCgSIgBgRQAAglAWgUQAWgUAmAAQAbAAARAMQARAMAAATQAAAMgGAFQgGAGgLAAQgIAAgGgDQgGgEgEgGIgFgJQgIgRgOAAQgJAAgFAGQgGAGAAAJIAGAbQAEAVABAQIAjAAQAGAAACADQACACAAAHIAAAFQAAAHgCACQgDADgFAAIgjAAIAAB6QAAAfACAJQACAKAFACIAJAEQAOAEAAAKQAAAJgLAEQgMADgiAAQgjAAgMgEg");
	this.shape_5.setTransform(33.5,3.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AA0B5QgDgDAAgIIAAgRIgBgBIgBgBQgDAAgFAGIgDAEQgMALgOAGQgOAGgRAAQgSAAgQgHQgQgHgKgMQgMgOgEgTQgFgTAAgyIAAgRIAAgRIAAgFQAAgUgCgFQgDgGgJgDIgJgDQgOgDAAgJQAAgGAFgEQAFgEARgGIAggIIAZgEQAHAAADAFQADAFAAAKIgBAKIgCBZQAAAwAKATQAKASAYAAQAbAAAMgYQAMgYAAg6IAAgSQAAgTgDgFQgDgGgIgDIgKgDQgNgDAAgJQAAgGAFgEQAEgEARgGIAggIIAZgEQAHAAADAFQADAEAAALIAAAOIgDBhIAAApIACAQQACAJAMAFIAAAAIAEACQAOAEAAAIQAAAGgEAEQgFAEgKAEIgiALQgQAEgJAAQgHAAgDgEg");
	this.shape_6.setTransform(10.3,8.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AgMCQQgMgEgJgIQgIgIgEgNQgDgNAAgkIAAh/IgWAAIgHgCIgCgHIAAgFQAAgIAZgVIAKgJIAJgHQAZgXAJAAIAHACQACACAAAEIAAAtIA2AAQAGAAADACQABADAAAGIAAAGQABAHgDACQgCADgGAAIgyAAIgDACIgBAFIAAB2QAAAfAFAIQAFAIAOgBQAIAAAMgDIAQgEQAFAAAEADQADADAAAFQAAANgUANQgVALgZABQgPgBgLgDg");
	this.shape_7.setTransform(-12.1,6.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("Ag7CtQgagGgRgKQgKgGgFgUQgHgVAAgbQAAgLAEgFQAEgGAIAAQALAAAMAVIAGAKQAPAbASAMQASAMAZAAQAZAAATgPQASgQAAgXQgBghhGgfIgHgDQg7gZgTgVQgSgVgBgiQABgrAfgbQAggcAzAAIAbACIAhAIIAKgGIAIgDQAGAAAFAEQAEAEAFAJQAIAOAFAQQAEAQABAMQgBAIgDAEQgEAFgHAAQgNAAgMgSIgDgEQgNgSgQgIQgQgJgUAAQgbAAgPANQgPAMAAAWQAAATANANQANANAyAWIAKAEQArASATAQQANAMAHARQAHAQAAATQAAAxgiAbQgjAbg7AAQgeAAgagFg");
	this.shape_8.setTransform(-34.6,3.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AhNBaQgigjAAg0QAAg2AjglQAjgjA1gBQAuABAcAaQAaAaAAAsQAAAPgEAFQgEAFgSAAIhbAAQgIAAgEgEQgFgEAAgHQAAgGAFgDQAEgEAIABIAxAAIAMgDQADgBAAgFQAAgYgPgPQgQgQgVAAQgdAAgOAZQgOAYAAAkQAAAlAUAaQATAbAdAAQASABAMgEQAMgEAMgIIAIgHQAMgJAHAAQAFAAAEACQADAEAAAFQAAAFgGAJQgGAJgKAHQgVASgTAHQgTAIgXAAQgygBgigig");
	this.shape_9.setTransform(-74.2,8.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AAhCsQgMgFAAgIQAAgKAMgEIAJgEQAGgDACgKQACgKAAgaQAAhNgKgSQgJgTgagBQgLABgMAHQgLAIgHAMQgFAKgCATQgCASAAAvQAAAYACAHQACAJAFACIAJAEQAMAEAAAKQAAAIgMAFQgLADgfAAQgmAAgLgDQgMgEAAgLQAAgIAMgEIAGgDQAGgDADgLQADgKAAgaIAAgnIAAgkIgChsQgBgagDgGQgDgCgOgFQgOgEgBgIQAAgGAHgFQAFgEAWgJIAXgGIAXgDQAHAAAEAFQADAFAAALIgBAKIgCBeIAAANIACAFIAEACIAEgFIAJgKQAMgMANgFQANgHAPAAQApABAUAaQAUAbAAA0IAAAXIAAAqIAAAOQAAAMADAGQACAFAFADIAGACQAMAFAAAIQABALgMAEQgLADgmAAQgfAAgMgDg");
	this.shape_10.setTransform(-101.4,3.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AgMCQQgMgEgIgIQgJgIgDgNQgEgNAAgkIAAh/IgWAAIgHgCIgCgHIAAgFQAAgIAZgVIAKgJIAKgHQAYgXAJAAIAHACQADACAAAEIAAAtIA1AAQAGAAACACQADADAAAGIAAAGQAAAHgDACQgDADgFAAIgyAAIgDACIgCAFIAAB2QAAAfAGAIQAFAIAOgBQAHAAAMgDIARgEQAFAAADADQAEADAAAFQAAANgVANQgTALgbABQgNgBgMgDg");
	this.shape_11.setTransform(-123.6,6.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thestuffing, new cjs.Rectangle(-134.3,-27.3,268.7,60.8), null);


(lib.thesides = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgZAaQgLgLAAgPQAAgPALgLQAKgKAPAAQAQAAAKAKQALALAAAPQAAAPgLALQgLALgPAAQgPAAgKgLg");
	this.shape.setTransform(99.6,17.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AgRB9IgZgFIgIAFIgIABIgEgBIgGgEQgHgGgHgTQgHgUAAgSQAAgHAEgFQAFgGAFAAQALABAMATIAJAOQAHAJAMAGQAMAGAOgBQAQABAJgIQAJgIAAgOQAAgTgngUIgOgHQglgSgOgPQgMgQAAgWQAAggAVgTQAWgUAiAAIAQABIARAEIAMgFIAHgCQAMABALASQALATAAAVQAAAJgDAEQgEAFgHAAQgGAAgFgFQgFgEgHgMQgKgPgJgFQgJgHgOAAQgMABgJAHQgIAJAAAMQAAALAIAIQAJAJAcAOIADACQBDAgAAAmQAAAigZAWQgaAXgmAAg");
	this.shape_1.setTransform(82.6,8.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AhNBaQgigjAAg0QAAg2AjglQAjgjA1gBQAuABAcAaQAaAaAAAsQAAAPgEAFQgEAFgSAAIhbAAQgIAAgEgEQgFgEAAgHQAAgGAFgDQAEgEAIABIAxAAIAMgDQADgBAAgFQAAgYgPgPQgQgQgVAAQgdAAgOAZQgOAYAAAkQAAAlAUAaQATAbAdAAQASABAMgEQAMgEAMgIIAIgHQAMgJAHAAQAFAAAEACQADAEAAAFQAAAFgGAJQgGAJgKAHQgVASgTAHQgTAIgXAAQgygBgigig");
	this.shape_2.setTransform(59.8,8.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AhoCRQgcghAAg0QAAg5AggkQAgglAzAAIARACQAHACAFAGQADAEAAAHQAAAMgPAAIgHAAIgGgBQgbAAgPAXQgQAUAAAmQAAAoARAZQARAZAbAAQAZAAAOgNQANgOAAgbIAAhCIAAhtQAAgRgDgGQgDgHgJgDIgGgCQgPgEAAgIQAAgGAGgGQAGgEASgHIAagHIAXgDQAIAAADAEQAEAGAAAKIgBAMIgCCTIACBkQABAXAEADIARAGQAMACAAAJQAAALgiALIgYAGIgSACQgHAAgDgDQgDgFAAgIIAAgLIgBgEIgBgCIgHAFIgLAIQgOAKgNAGQgOAFgOAAQgtAAgcggg");
	this.shape_3.setTransform(33.8,3.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AgqCrQgMgEAAgLQAAgIAMgEIAGgDQAHgDACgIQADgIAAgSIgBgQIAAgUIAAgYQAAgmgCgLQgCgLgEgDIgMgEQgOgEAAgIQAAgGAEgEQAFgEAKgEIAkgMIAZgEQAGAAADAEQADAFAAALIAAAOIgBALIgBA8IAAABIgBA7QAAAXACAJQACAKAFACIAJAEQAMAFAAAJQAAAJgMAEQgLAEgfAAQgkAAgMgEgAgdh4QgKgIAAgNQAAgNALgKQAMgKAQAAQAOAAALAJQAKAJAAANQAAANgLAJQgMAJgPAAQgQAAgKgIg");
	this.shape_4.setTransform(11.9,3.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("Ag6CtQgbgGgRgKQgJgGgHgUQgGgVAAgbQAAgLAEgFQAFgGAHAAQALAAAMAVIAGAKQAPAbASAMQASAMAZAAQAaAAASgPQARgQABgXQAAghhHgfIgIgDQg5gZgTgVQgUgVAAgiQAAgrAggbQAggcAyAAIAcACIAhAIIAKgGIAIgDQAGAAAEAEQAFAEAFAJQAIAOAFAQQAEAQAAAMQAAAIgDAEQgEAFgHAAQgMAAgMgSIgEgEQgOgSgQgIQgPgJgUAAQgaAAgQANQgPAMAAAWQAAATANANQANANAyAWIAKAEQArASATAQQANAMAHARQAHAQAAATQAAAxgiAbQgjAbg7AAQgdAAgagFg");
	this.shape_5.setTransform(-8.6,3.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AhNBaQgigjAAg0QAAg2AjglQAjgjA1gBQAuABAcAaQAaAaAAAsQAAAPgEAFQgEAFgSAAIhbAAQgIAAgEgEQgFgEAAgHQAAgGAFgDQAEgEAIABIAxAAIAMgDQADgBAAgFQAAgYgPgPQgQgQgVAAQgdAAgOAZQgOAYAAAkQAAAlAUAaQATAbAdAAQASABAMgEQAMgEAMgIIAIgHQAMgJAHAAQAFAAAEACQADAEAAAFQAAAFgGAJQgGAJgKAHQgVASgTAHQgTAIgXAAQgygBgigig");
	this.shape_6.setTransform(-48.3,8.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AAhCsQgMgFAAgIQAAgKAMgEIAJgEQAGgDACgKQACgKAAgaQAAhNgKgSQgJgTgagBQgLABgLAHQgNAIgFAMQgGAKgCATQgCASAAAvQAAAYACAHQACAJAFACIAJAEQAMAEAAAKQAAAIgLAFQgMADgfAAQglAAgMgDQgMgEAAgLQAAgIAMgEIAGgDQAHgDACgLQADgKAAgaIAAgnIAAgkIgChsQgBgagDgGQgDgCgPgFQgOgEAAgIQABgGAFgFQAGgEAVgJIAZgGIAVgDQAJAAADAFQADAFAAALIAAAKIgCBeIAAANIABAFIADACIAGgFIAIgKQAMgMANgFQANgHAPAAQApABAUAaQAUAbAAA0IABAXIAAAqIAAAOQAAAMACAGQADAFAFADIAFACQAMAFABAIQAAALgMAEQgMADglAAQgfAAgMgDg");
	this.shape_7.setTransform(-75.5,3.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AgMCQQgMgEgJgIQgIgIgDgNQgEgNAAgkIAAh/IgWAAIgHgCIgCgHIAAgFQAAgIAZgVIAKgJIAJgHQAZgXAJAAIAHACQACACABAEIAAAtIA1AAQAGAAADACQABADAAAGIAAAGQAAAHgCACQgCADgGAAIgyAAIgDACIgBAFIAAB2QgBAfAGAIQAFAIAOgBQAIAAAMgDIAQgEQAFAAADADQAEADAAAFQAAANgUANQgVALgaABQgOgBgLgDg");
	this.shape_8.setTransform(-97.7,6.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thesides, new cjs.Rectangle(-108.3,-27.3,216.7,60.8), null);


(lib.thedesserts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgZAaQgLgLAAgPQAAgPALgLQAKgKAPAAQAQAAAKAKQALALAAAPQAAAPgLALQgLALgPAAQgPAAgKgLg");
	this.shape.setTransform(134.1,17.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AgSB9IgYgFIgIAFIgHABIgFgBIgFgEQgIgGgHgTQgHgUAAgSQAAgHAEgFQAFgGAFAAQAMABALATIAJAOQAHAJANAGQAMAGANgBQAQABAJgIQAJgIAAgOQAAgTgngUIgOgHQglgSgNgPQgOgQAAgWQABggAVgTQAWgUAiAAIAQABIASAEIALgFIAHgCQAMABALASQALATAAAVQAAAJgEAEQgDAFgHAAQgGAAgFgFQgFgEgHgMQgJgPgKgFQgKgHgNAAQgMABgJAHQgJAJABAMQgBALAJAIQAJAJAdAOIACACQBDAgAAAmQAAAigZAWQgbAXglAAg");
	this.shape_1.setTransform(117,8.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AgMCQQgMgEgIgIQgJgIgEgNQgDgNAAgkIAAh/IgWAAIgGgCIgDgHIAAgFQAAgIAZgVIAKgJIAJgHQAZgXAJAAIAHACQACACAAAEIAAAtIA2AAQAGAAACACQACADAAAGIAAAGQAAAHgCACQgDADgFAAIgxAAIgEACIgCAFIAAB2QABAfAFAIQAFAIAOgBQAHAAAMgDIARgEQAFAAAEADQADADAAAFQAAANgUANQgUALgaABQgOgBgMgDg");
	this.shape_2.setTransform(98.5,6.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AhHB3QgNgEAAgLQAAgIAMgEIAGgDQAHgDACgJQADgHAAgSIAAgQIAAgUIAAgOQAAgsgDgMQgCgOgEgDIgMgEQgOgEAAgJQAAgFAEgEQAFgFALgEIAggKIAVgEQAMAAADAgIABAFIABABQAMgTAOgLQANgJAOgBQARABAJAJQAKALAAAQQAAARgIAJQgHAKgNAAIgNgDIgKgHIgFgJQgDgGgCAAQgRAAgHAXQgFAWAABJQAAAUACALQACAKAHADIAJADQAPAFAAAKQAAAIgOAFQgMADghAAQgkAAgLgDg");
	this.shape_3.setTransform(81.3,8.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AhNBaQgigjAAg0QAAg2AjglQAjgjA1gBQAuABAcAaQAaAaAAAsQAAAPgEAFQgEAFgSAAIhbAAQgIAAgEgEQgFgEAAgHQAAgGAFgDQAEgEAIABIAxAAIAMgDQADgBAAgFQAAgYgPgPQgQgQgVAAQgdAAgOAZQgOAYAAAkQAAAlAUAaQATAbAdAAQASABAMgEQAMgEAMgIIAIgHQAMgJAHAAQAFAAAEACQADAEAAAFQAAAFgGAJQgGAJgKAHQgVASgTAHQgTAIgXAAQgygBgigig");
	this.shape_4.setTransform(59,8.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AgRB9IgagFIgHAFIgIABIgEgBIgGgEQgHgGgHgTQgHgUAAgSQAAgHAEgFQAFgGAGAAQAKABAMATIAJAOQAHAJAMAGQANAGANgBQAQABAJgIQAJgIAAgOQAAgTgngUIgOgHQglgSgOgPQgNgQABgWQgBggAWgTQAWgUAjAAIAPABIARAEIAMgFIAHgCQAMABALASQALATAAAVQAAAJgDAEQgEAFgHAAQgGAAgFgFQgFgEgIgMQgJgPgJgFQgJgHgOAAQgNABgIAHQgIAJgBAMQABALAIAIQAJAJAcAOIAEACQBCAgAAAmQAAAigaAWQgZAXgnAAg");
	this.shape_5.setTransform(36,8.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AgSB9IgYgFIgIAFIgIABIgEgBIgFgEQgIgGgHgTQgHgUAAgSQAAgHAEgFQAFgGAFAAQAMABALATIAJAOQAHAJANAGQAMAGANgBQAQABAJgIQAJgIAAgOQAAgTgngUIgOgHQglgSgNgPQgOgQAAgWQABggAVgTQAWgUAiAAIAQABIASAEIALgFIAHgCQAMABALASQALATAAAVQAAAJgEAEQgDAFgHAAQgGAAgFgFQgFgEgHgMQgJgPgKgFQgKgHgNAAQgMABgJAHQgJAJABAMQgBALAJAIQAJAJAdAOIACACQBDAgAAAmQAAAigZAWQgbAXglAAg");
	this.shape_6.setTransform(15.3,8.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AhNBaQgigjAAg0QAAg2AjglQAjgjA1gBQAuABAcAaQAaAaAAAsQAAAPgEAFQgEAFgSAAIhbAAQgIAAgEgEQgFgEAAgHQAAgGAFgDQAEgEAIABIAxAAIAMgDQADgBAAgFQAAgYgPgPQgQgQgVAAQgdAAgOAZQgOAYAAAkQAAAlAUAaQATAbAdAAQASABAMgEQAMgEAMgIIAIgHQAMgJAHAAQAFAAAEACQADAEAAAFQAAAFgGAJQgGAJgKAHQgVASgTAHQgTAIgXAAQgygBgigig");
	this.shape_7.setTransform(-7.5,8.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AgzCsIgeAAIgUAAIgUABQgdAAgJgFQgJgDAAgKQAAgJAMgGQANgEADgEQACgFACgkIADhcIgDhYQgCglgCgEQgDgEgNgFQgMgFAAgKQAAgJAKgEQAKgEAcAAIAVABIAYAAIAggBIAbgBQBZAAAwAuQAwAuAABUQAABTgxArQgxArhfAAgAg0iHQgLAEgDAHQgDAJgBAcIgCBJIACBaQABAmADAHQADAHAQAFQAQAGAVAAQA3AAAcgiQAbggAAhEQgBhFgfgmQgfglg7AAQgTAAgLAEg");
	this.shape_8.setTransform(-38.7,3.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AhNBaQgigjAAg0QAAg2AjglQAjgjA1gBQAuABAcAaQAaAaAAAsQAAAPgEAFQgEAFgSAAIhbAAQgIAAgEgEQgFgEAAgHQAAgGAFgDQAEgEAIABIAxAAIAMgDQADgBAAgFQAAgYgPgPQgQgQgVAAQgdAAgOAZQgOAYAAAkQAAAlAUAaQATAbAdAAQASABAMgEQAMgEAMgIIAIgHQAMgJAHAAQAFAAAEACQADAEAAAFQAAAFgGAJQgGAJgKAHQgVASgTAHQgTAIgXAAQgygBgigig");
	this.shape_9.setTransform(-82.7,8.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006F46").s().p("AAhCsQgMgFAAgIQAAgKAMgEIAJgEQAGgDACgKQACgKAAgaQAAhNgKgSQgJgTgagBQgLABgLAHQgMAIgGAMQgGAKgCATQgCASAAAvQAAAYACAHQACAJAFACIAJAEQAMAEAAAKQAAAIgLAFQgMADgfAAQglAAgMgDQgMgEAAgLQAAgIAMgEIAGgDQAHgDACgLQADgKAAgaIAAgnIAAgkIgChsQgBgagDgGQgDgCgOgFQgOgEgBgIQAAgGAHgFQAFgEAWgJIAYgGIAVgDQAJAAADAFQADAFAAALIAAAKIgDBeIAAANIACAFIAEACIAEgFIAJgKQAMgMANgFQANgHAPAAQApABAUAaQAUAbAAA0IAAAXIAAAqIAAAOQAAAMADAGQACAFAGADIAFACQANAFAAAIQAAALgMAEQgMADglAAQgfAAgMgDg");
	this.shape_10.setTransform(-109.9,3.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006F46").s().p("AgMCQQgMgEgJgIQgIgIgDgNQgEgNAAgkIAAh/IgWAAIgHgCIgCgHIAAgFQAAgIAZgVIAKgJIAKgHQAYgXAJAAIAHACQADACAAAEIAAAtIA1AAQAGAAADACQACADAAAGIAAAGQgBAHgCACQgCADgGAAIgyAAIgDACIgBAFIAAB2QgBAfAGAIQAFAIAOgBQAIAAALgDIARgEQAFAAADADQAEADAAAFQAAANgVANQgTALgbABQgNgBgMgDg");
	this.shape_11.setTransform(-132.1,6.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thedesserts, new cjs.Rectangle(-142.8,-27.3,285.6,60.8), null);


(lib.thecredit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("AgZAaQgLgLAAgPQAAgPALgLQAKgKAPAAQAQAAAKAKQALALAAAPQAAAPgLALQgLALgPAAQgPAAgKgLg");
	this.shape.setTransform(109.5,17.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006F46").s().p("AgMCQQgMgEgIgIQgJgIgEgNQgDgNAAgkIAAh/IgWAAIgGgCIgDgHIAAgFQAAgIAZgVIAKgJIAKgHQAYgXAJAAIAHACQACACAAAEIAAAtIA2AAQAGAAACACQACADABAGIAAAGQAAAHgDACQgCADgGAAIgxAAIgEACIgCAFIAAB2QAAAfAGAIQAFAIAOgBQAHAAAMgDIARgEQAFAAAEADQADADAAAFQAAANgVANQgTALgbABQgOgBgLgDg");
	this.shape_1.setTransform(94.5,6.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006F46").s().p("AgqCrQgMgEAAgLQAAgIAMgEIAGgDQAHgDACgIQADgIAAgSIgBgQIAAgUIAAgYQAAgmgCgLQgCgLgEgDIgMgEQgOgEAAgIQAAgGAEgEQAFgEAKgEIAkgMIAZgEQAGAAADAEQADAFAAALIAAAOIgBALIgBA8IAAABIgBA7QAAAXACAJQACAKAFACIAJAEQAMAFAAAJQAAAJgMAEQgLAEgfAAQgkAAgMgEgAgdh4QgKgIAAgNQAAgNALgKQAMgKAQAAQAOAAALAJQAKAJAAANQAAANgLAJQgMAJgPAAQgQAAgKgIg");
	this.shape_2.setTransform(79,3.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006F46").s().p("AhoCRQgcghAAg0QAAg5AggkQAgglAzAAIARACQAHACAFAGQADAEAAAHQAAAMgPAAIgHAAIgGgBQgbAAgPAXQgQAUAAAmQAAAoARAZQARAZAbAAQAZAAAOgNQANgOAAgbIAAhCIAAhtQAAgRgDgGQgDgHgJgDIgGgCQgPgEAAgIQAAgGAGgGQAGgEASgHIAagHIAXgDQAIAAADAEQAEAGAAAKIgBAMIgCCTIACBkQABAXAEADIARAGQAMACAAAJQAAALgiALIgYAGIgSACQgHAAgDgDQgDgFAAgIIAAgLIgBgEIgBgCIgHAFIgLAIQgOAKgNAGQgOAFgOAAQgtAAgcggg");
	this.shape_3.setTransform(59,3.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006F46").s().p("AhNBaQgigjAAg0QAAg2AjglQAjgjA1gBQAuABAcAaQAaAaAAAsQAAAPgEAFQgEAFgSAAIhbAAQgIAAgEgEQgFgEAAgHQAAgGAFgDQAEgEAIABIAxAAIAMgDQADgBAAgFQAAgYgPgPQgQgQgVAAQgdAAgOAZQgOAYAAAkQAAAlAUAaQATAbAdAAQASABAMgEQAMgEAMgIIAIgHQAMgJAHAAQAFAAAEACQADAEAAAFQAAAFgGAJQgGAJgKAHQgVASgTAHQgTAIgXAAQgygBgigig");
	this.shape_4.setTransform(31.4,8.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006F46").s().p("AhIB3QgMgEAAgLQAAgIAMgEIAGgDQAGgDADgJQADgHAAgSIgBgQIAAgUIAAgOQAAgsgCgMQgBgOgGgDIgKgEQgPgEAAgJQAAgFAFgEQADgFAMgEIAfgKIAWgEQALAAAEAgIABAFIABABQANgTANgLQANgJAOgBQAQABAKAJQAKALAAAQQAAARgHAJQgIAKgOAAIgMgDIgJgHIgGgJQgDgGgCAAQgRAAgGAXQgGAWAABJQAAAUACALQADAKAGADIAKADQAOAFAAAKQAAAIgNAFQgOADgfAAQglAAgMgDg");
	this.shape_5.setTransform(10.3,8.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006F46").s().p("AglCnQgfgMgZgWQgcgZgOgkQgPgjAAgpQAAghAKgdQAKgdATgXQAXgdAigPQAhgPAngBIAeADIAuAKIAFgBIASgFIAIADIAHAGQAIAOAEASQAGASAAAOQAAALgFAEQgDAFgIABQgKgBgSgVIgQgRQgMgNgTgIQgUgHgWAAQguAAgbAhQgbAfAAA4QAABGAjAtQAhAuA0AAQAVAAATgGQATgHALgMIAMgOQALgOAGAAQAHAAAEAGQADAHABALQAAAWgHANQgGANgLAAIgCAAIgDgBQgWAMgXAGQgWAFgYAAQgkAAgggLg");
	this.shape_6.setTransform(-15.6,3.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006F46").s().p("AhNBaQgigjAAg0QAAg2AjglQAjgjA1gBQAuABAcAaQAaAaAAAsQAAAPgEAFQgEAFgSAAIhbAAQgIAAgEgEQgFgEAAgHQAAgGAFgDQAEgEAIABIAxAAIAMgDQADgBAAgFQAAgYgPgPQgQgQgVAAQgdAAgOAZQgOAYAAAkQAAAlAUAaQATAbAdAAQASABAMgEQAMgEAMgIIAIgHQAMgJAHAAQAFAAAEACQADAEAAAFQAAAFgGAJQgGAJgKAHQgVASgTAHQgTAIgXAAQgygBgigig");
	this.shape_7.setTransform(-58.1,8.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006F46").s().p("AAhCsQgMgFAAgIQAAgKAMgEIAJgEQAGgDACgKQACgKAAgaQAAhNgKgSQgJgTgZgBQgMABgLAHQgNAIgFAMQgGAKgCATQgCASAAAvQAAAYACAHQACAJAFACIAJAEQAMAEAAAKQAAAIgLAFQgNADgeAAQgmAAgLgDQgMgEAAgLQAAgIAMgEIAGgDQAHgDACgLQADgKAAgaIAAgnIAAgkIgBhsQgCgagEgGQgCgCgPgFQgNgEAAgIQAAgGAFgFQAGgEAVgJIAZgGIAVgDQAJAAADAFQADAFAAALIAAAKIgCBeIAAANIABAFIADACIAGgFIAIgKQAMgMAOgFQAMgHAPAAQApABAUAaQAUAbAAA0IABAXIAAAqIAAAOQgBAMADAGQADAFAFADIAGACQALAFABAIQAAALgMAEQgMADglAAQgfAAgMgDg");
	this.shape_8.setTransform(-85.3,3.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006F46").s().p("AgMCQQgMgEgJgIQgIgIgEgNQgDgNAAgkIAAh/IgWAAIgHgCIgCgHIAAgFQAAgIAZgVIAKgJIAJgHQAZgXAJAAIAHACQACACAAAEIAAAtIA2AAQAGAAADACQABADAAAGIAAAGQABAHgDACQgCADgGAAIgyAAIgDACIgBAFIAAB2QAAAfAFAIQAFAIAOgBQAIAAAMgDIAQgEQAFAAAEADQADADAAAFQAAANgUANQgVALgZABQgPgBgLgDg");
	this.shape_9.setTransform(-107.5,6.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thecredit, new cjs.Rectangle(-118.2,-27.3,236.4,60.8), null);


(lib.ordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAXAwIgXhMIAAAAIgWBMIgOAAIgchfIAOAAIAVBLIAXhLIANAAIAXBLIAAAAIAVhLIAOAAIgcBfg");
	this.shape.setTransform(35.8,0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgKAxIgJgDQgJgDgHgHQgHgHgEgJQgEgJAAgLQAAgKAEgKQAEgJAHgGQAHgHAJgEIAJgCIAKgBQALAAAJADIAJAFIAHAGQAHAGAEAJQAEAKAAAKQAAALgEAJQgEAJgHAHIgHAGIgJAEQgJAEgLAAIgKgBgAgOgjQgHAEgEAFQgFAFgDAHQgCAHAAAHQAAAIACAHQADAHAFAFQAFAFAGADQAHADAHAAQAIAAAHgDQAHgDAEgFQAFgFADgHQACgHAAgIQAAgHgCgHQgDgHgFgFQgEgFgHgEQgHgDgIAAQgHAAgHADg");
	this.shape_1.setTransform(23.4,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAXAwIgxhNIAABNIgOAAIAAhfIASAAIAxBMIAAhMIANAAIAABfg");
	this.shape_2.setTransform(12.5,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AASAwIgXgrIgPAAIAAArIgNAAIAAhfIAfAAIAMACQAGABAEADQAFADADAFQADAFAAAIQAAAKgHAHIgHAEIgKADIAbAsgAgUgFIAQAAIAHgBIAHgCQAEgCABgDQACgDAAgEQAAgFgCgDIgEgEIgHgDIgHAAIgRAAg");
	this.shape_3.setTransform(0.2,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgfAwIAAhfIA9AAIAAAMIgvAAIAAAdIAsAAIAAAKIgsAAIAAAgIAxAAIAAAMg");
	this.shape_4.setTransform(-8.1,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgpAwIAAhfIAhAAQAIAAAJADQAJADAIAFQAHAGAFAJIADAKIABALIgBALIgDAKIgGAIIgGAHQgIAGgJADQgLADgGAAgAgcAkIARAAQAJAAAGgCQAHgDAGgEQAFgFADgHIACgHIABgIIgBgHIgCgIQgDgGgFgFQgGgEgHgDQgGgCgJAAIgRAAg");
	this.shape_5.setTransform(-17.3,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AASAwIgXgrIgPAAIAAArIgNAAIAAhfIAfAAIAMACQAGABAEADQAFADADAFQADAFAAAIQAAAKgHAHIgHAEIgKADIAbAsgAgUgFIAQAAIAHgBIAHgCQAEgCABgDQACgDAAgEQAAgFgCgDIgEgEIgHgDIgHAAIgRAAg");
	this.shape_6.setTransform(-26.4,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgKAxIgJgDQgJgDgHgHQgHgHgEgJQgEgJAAgLQAAgKAEgKQAEgJAHgGQAHgHAJgEIAJgCIAKgBQALAAAJADIAJAFIAHAGQAHAGAEAJQAEAKAAAKQAAALgEAJQgEAJgHAHIgHAGIgJAEQgJAEgLAAIgKgBgAgOgjQgHAEgEAFQgFAFgDAHQgCAHAAAHQAAAIACAHQADAHAFAFQAFAFAGADQAHADAHAAQAIAAAHgDQAHgDAEgFQAFgFADgHQACgHAAgIQAAgHgCgHQgDgHgFgFQgEgFgHgEQgHgDgIAAQgHAAgHADg");
	this.shape_7.setTransform(-36.7,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ordernow, new cjs.Rectangle(-44.5,-10.3,89,20.6), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.logokale = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(130.4,59.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgVgDgGgEQgKgFAAgNQAAgKAFgHQAHgHAIAAIARAAQAKAAAFgLQACgKABgXIAAl5QgBgXgCgKQgFgLgKAAIgRAAQgIAAgHgHQgFgHAAgKQAAgNAKgFQAGgEAVgDQBdgNBrAAQBOAAA2ASQA0ASAnAoQAlAlAUA5QAUA4AABEQAABNgZA9QgaA+guAlQglAegxAOQgwAOhFAAQhrAAhdgNgAgwjrQgcAFgJALQgKAMAAAhIAAFjQAAAhAUALQAOAHAnADQBMAEAthAQAqg/AAhwQAAhwgqg/Qgrg/hKAAIgeADg");
	this.shape_1.setTransform(62.2,30.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(81.2,88.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(52.4,88.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(22.6,88.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAuBeIgfgyQgGgJgKAAIgtAAQgDAAgEADQgEAEABADIAAAyQAAAGgKACIgPAAQgMAAAAgMIAAi5QgBgIAKAAIBqAAQAgAAAUATQAVATAAAfQAAAYgPAPQgIAJgPAKQgHAGADAGIAjAyQAFAIgFADQgEAFgPAAQgQAAgHgJgAg4g4IAAAuQAAAFAEADQAEACAFAAIA+AAQAQAAALgIQALgIAAgRQAAgQgLgJQgLgJgQABIg+AAQgNAAAAAKg");
	this.shape_5.setTransform(-11.1,88.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAAAABgBQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-44.3,88.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBkQgFgDAAgEIgOhsQgCgGgFAAQgDAAgDADIgxA+QgEAGgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBoQgCALgTAAQgGAAgFgDQgGgDAAgFIAViwQACgJADgEQAEgEALAAQAKAAAFAJIA4BPQAFAHAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAIIAVC1QABALgXAAQgFAAgFgDg");
	this.shape_7.setTransform(-78.1,88.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(14.6,-54.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDwQhFg1gYheIgBgCQgCgMgHAAQgGAAgCALIgBACQgYBfhGA1QhIA3hoAAQh+AAhMhQQhMhQAAiFQAAiHBMhRQBLhQCAAAQBpAABHA3QBHA2AXBgQACALAGAAQAHgBACgKIABgBQAXhgBGg1QBHg3BoAAQB/AABNBQQBMBPAACFQAACHhMBRQhNBRiBAAQhmAAhHg3gACniqQgpA/AABuQAABrApA/QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/gAmFiqQgoA/AABuQAABsAoA+QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/g");
	this.shape_9.setTransform(-21,30.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-98.4,30.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIIAJgFQAEgCAFAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(110.1,30.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAHQgNAJgQAAQgTAAgKgJQgLgJgJgYIimm+QgKgagHgHQgHgHgUgFQgOgCgFgFQgFgFAAgLQAAgVAdgBICvAAQAcAAAAAYQAAAKgHAFQgHAFgRABQgOACgGAFQgGAFAAAJQAAAJADAKIBzFHQACAGAFgBQAEAAACgGIA/i2QAIgYgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgDgGgGQgFgEAAgKQAAgaAdAAICnAAQAdAAAAAYQAAASgcAEQgRACgFAFQgGAFAAAMQAAAKAIAZIBfEsQACAFAEAAQAFAAABgGIBdk6QAEgLAAgJQAAgSgdgEQgbgCAAgVQAAgNAHgGQAIgFARgBIElAAQAVABAIAFQAIAFAAAOQAAAKgGAIQgGAGgJAAIgQAAQgLAAgFALQgCAIAAAZIAABtQAAAeAFAGQAGAHAXAAIB0AAQAXAAAHgIQADgDAAgHIABgdIAAhpQAAgbgDgGQgFgLgKAAIgQAAQgKAAgHgGQgGgIAAgKQAAgOAIgFQAJgFAWgBICaAAQAWABAJAFQAJAFAAAOQAAAKgHAIQgGAGgJAAIgSAAQgEAAgEADQgFADgBAFQgDAJAAAYIAAF9QAAAXADAKQABAFAFACQAEADAEABIASAAQAJAAAGAGQAHAIAAAJQAAAOgJAFQgIAGgXAAIiaAAQgWAAgIgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIAQAAQAKAAAFgLQADgGAAgbIAAh8IgBgeQAAgHgDgEQgHgHgXAAIh0AAQgXAAgGAGQgFAHAAAdIAACCQAAAYACAJQAFALALAAIAQAAQAJAAAGAGQAGAIAAAKQAAAOgIAEQgIAGgVAAIiaAAQgWAAgJgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIARAAQAEgBAFgDQAEgCABgFQADgGAAgbIAAl9QAAgwgkAEQgLABgHAKQgIAIgGAWIiHGzQgJAfgKALQgLALgTAAQgTAAgLgJg");
	this.shape_12.setTransform(-74.6,-36.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgFAAgOQAAgKAGgHQAGgGAJAAIARAAQAEAAAEgDQAEgEACgEQADgIAAgXIAAl/QAAgZgDgJQgDgLgLABIgRAAQgKgBgGgGQgHgHAAgLQAAgNAJgGQAJgFAWAAICcAAQAWAAAJAFQAJAGAAANQAAALgGAHQgHAGgJABIgSAAQgOgBgDALQgDAGAAAcIAAFjQAAAdACAJQACAJAIAFQAGAEALACQALACAagBIAwAAQAvAAAPgfIAIgPQAIgQAPgBQAMAAAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(69.2,-37.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgDALgHAFQgHAFgOAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(114.4,-37.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZNQk7iFjyjyQjyjziFk6QiJlFAAljQAAlkCJlFQCFk6DyjzQDzjyE6iFQFFiJFjAAQFkAAFFCJQE6CFDyDyQDyDzCGE6QCJFFAAFkQAAFjiJFFQiGE6jyDzQjyDyk6CFQlFCJlkAAQljAAlFiJg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-175,-175,350,350);


(lib.interstitialholidaymainsstuffing = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialstuffing();
	this.instance.parent = this;
	this.instance.setTransform(-52,-46.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.interstitialholidaymainsstuffing, new cjs.Rectangle(-52,-46.5,104,93), null);


(lib.holidaymainstable = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialholidaymainstable();
	this.instance.parent = this;
	this.instance.setTransform(-160,-240);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainstable, new cjs.Rectangle(-160,-240,320,480), null);


(lib.holidaymainspotatoes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialholidaymainspotatoes();
	this.instance.parent = this;
	this.instance.setTransform(-70,-100);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainspotatoes, new cjs.Rectangle(-70,-100,140,200), null);


(lib.holidaymainscranberries = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialholidaymainscrannberries();
	this.instance.parent = this;
	this.instance.setTransform(-71.5,-46);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainscranberries, new cjs.Rectangle(-71.5,-46,143,92), null);


(lib.holidaymainscinnamonbuns = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialcinnamonbuns();
	this.instance.parent = this;
	this.instance.setTransform(-80.5,-54.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainscinnamonbuns, new cjs.Rectangle(-80.5,-54.5,161,109), null);


(lib.holidaymainsbrusselsprouts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialholidaymainsbrusselsprouts();
	this.instance.parent = this;
	this.instance.setTransform(-55.5,-95);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainsbrusselsprouts, new cjs.Rectangle(-55.5,-95,111,190), null);


(lib.holidaymainsapples = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.interstitialapples();
	this.instance.parent = this;
	this.instance.setTransform(-74,-31);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainsapples, new cjs.Rectangle(-74,-31,148,62), null);


(lib.ctarectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AqlCtIAAlZIVLAAIAAFZg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangle, new cjs.Rectangle(-67.7,-17.2,135.6,34.5), null);


(lib.blackrectangleinbox = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("EgXbgkQMAu3AAAMAAABIhMgu3AAAg");
	this.shape.setTransform(0,0,1.063,1.032);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-160.5,-240.5,321,481);


// stage content:
(lib.interstitialholidaymains = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_48 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_292 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(48).call(this.frame_48).wait(244).call(this.frame_292).wait(19));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(160.4,240.1,1.553,0.731,0,0,0,0.2,0.1);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(311));

	// black-rectangle
	this.instance = new lib.blackrectangleinbox("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(160,240);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(311));

	// logo
	this.instance_1 = new lib.logokale("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(160,37,0.269,0.269,0,0,0,0,0.2);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({regY:0,scaleX:0.05,scaleY:0.05},0).to({regX:0.1,regY:0.1,scaleX:0.29,scaleY:0.29,y:37.1,alpha:1},6).to({regX:0,regY:0.2,scaleX:0.27,scaleY:0.27},8).wait(288));

	// fade-from-white
	this.instance_2 = new lib.whiterectanglefade();
	this.instance_2.parent = this;
	this.instance_2.setTransform(172.5,253.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({alpha:0},9).wait(302));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AzrQmIAAqVMAtCAAAIAAKVg");
	mask.setTransform(162.3,106.2);

	// well-make
	this.instance_3 = new lib.wellmake();
	this.instance_3.parent = this;
	this.instance_3.setTransform(160,174.1);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(44).to({x:-145},0).to({x:170,alpha:1},10,cjs.Ease.get(1)).to({x:160},8,cjs.Ease.get(1)).wait(182).to({alpha:0},5).wait(62));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("A0QUzIAAqUMAtnAAAIAAKUg");
	mask_1.setTransform(162.3,133.2);

	// the-turkey
	this.instance_4 = new lib.theturkey();
	this.instance_4.parent = this;
	this.instance_4.setTransform(160,227.6);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(52).to({x:-145},0).to({x:170,alpha:1},10,cjs.Ease.get(1)).to({x:160},8,cjs.Ease.get(1)).wait(30).to({alpha:0},5).wait(206));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("Aw5QmIAAqVMAqQAAAIAAKVg");
	mask_2.setTransform(162.3,106.2);

	// you-take
	this.instance_5 = new lib.youtake();
	this.instance_5.parent = this;
	this.instance_5.setTransform(160,174.1);
	this.instance_5.alpha = 0;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(268).to({x:-145},0).to({x:170,alpha:1},10,cjs.Ease.get(1)).to({x:160},8,cjs.Ease.get(1)).wait(25));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("A1WUzIAAqUMAutAAAIAAKUg");
	mask_3.setTransform(162.3,133.2);

	// the-stuffing
	this.instance_6 = new lib.thestuffing();
	this.instance_6.parent = this;
	this.instance_6.setTransform(160,227.6);
	this.instance_6.alpha = 0;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(100).to({x:-145,alpha:1},0).to({x:170},10,cjs.Ease.get(1)).to({x:160},8,cjs.Ease.get(1)).wait(30).to({alpha:0},5).wait(158));

	// mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("Aw5UzIAAqUMAqQAAAIAAKUg");
	mask_4.setTransform(162.3,133.2);

	// the-sides
	this.instance_7 = new lib.thesides();
	this.instance_7.parent = this;
	this.instance_7.setTransform(160,227.6);
	this.instance_7.alpha = 0;

	var maskedShapeInstanceList = [this.instance_7];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(148).to({x:-145},0).to({x:170,alpha:1},10,cjs.Ease.get(1)).to({x:160},8,cjs.Ease.get(1)).wait(30).to({alpha:0},5).wait(110));

	// mask (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	mask_5.graphics.p("A2qUzIAAqUMAwBAAAIAAKUg");
	mask_5.setTransform(162.3,133.2);

	// the-desserts
	this.instance_8 = new lib.thedesserts();
	this.instance_8.parent = this;
	this.instance_8.setTransform(160,227.6);
	this.instance_8.alpha = 0;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(196).to({x:-145},0).to({x:170,alpha:1},10,cjs.Ease.get(1)).to({x:160},8,cjs.Ease.get(1)).wait(30).to({alpha:0},5).wait(62));

	// mask (mask)
	var mask_6 = new cjs.Shape();
	mask_6._off = true;
	mask_6.graphics.p("Ay0UZIAAqTMAsLAAAIAAKTg");
	mask_6.setTransform(162.3,130.6);

	// the-credit
	this.instance_9 = new lib.thecredit();
	this.instance_9.parent = this;
	this.instance_9.setTransform(160,227.6);
	this.instance_9.alpha = 0;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_6;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(278).to({x:-145},0).to({x:170,alpha:1},10,cjs.Ease.get(1)).to({x:160},8,cjs.Ease.get(1)).wait(15));

	// mask (mask)
	var mask_7 = new cjs.Shape();
	mask_7._off = true;
	mask_7.graphics.p("AxUMxIAAqVMAqrAAAIAAKVg");
	mask_7.setTransform(162.3,81.7);

	// we'll-make-the-feast
	this.instance_10 = new lib.wellmakethefeast();
	this.instance_10.parent = this;
	this.instance_10.setTransform(160,127.1);
	this.instance_10.alpha = 0;

	var maskedShapeInstanceList = [this.instance_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_7;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(255).to({x:-145},0).to({x:170,alpha:1},10,cjs.Ease.get(1)).to({x:160},8,cjs.Ease.get(1)).wait(38));

	// mask (mask)
	var mask_8 = new cjs.Shape();
	mask_8._off = true;
	mask_8.graphics.p("AtfZkIAAqVMAtCAAAIAAKVg");
	mask_8.setTransform(201.9,163.6);

	// order-now
	this.instance_11 = new lib.ordernow();
	this.instance_11.parent = this;
	this.instance_11.setTransform(160,293.1);
	this.instance_11.alpha = 0;

	var maskedShapeInstanceList = [this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_8;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(64).to({x:-145},0).to({x:170,alpha:1},10,cjs.Ease.get(1)).to({x:160},6,cjs.Ease.get(1)).wait(231));

	// mask (mask)
	var mask_9 = new cjs.Shape();
	mask_9._off = true;
	mask_9.graphics.p("AvTZkIAAqVMAtCAAAIAAKVg");
	mask_9.setTransform(190.3,163.6);

	// cta-rectangle
	this.instance_12 = new lib.ctarectangle();
	this.instance_12.parent = this;
	this.instance_12.setTransform(160,292.8);
	this.instance_12.alpha = 0;

	var maskedShapeInstanceList = [this.instance_12];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_9;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(64).to({x:-145},0).to({x:170,alpha:1},10,cjs.Ease.get(1)).to({x:160},6,cjs.Ease.get(1)).wait(231));

	// stuffing
	this.instance_13 = new lib.interstitialholidaymainsstuffing();
	this.instance_13.parent = this;
	this.instance_13.setTransform(52,46.5);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(9).to({alpha:1},10).wait(292));

	// cinnamon-buns
	this.instance_14 = new lib.holidaymainscinnamonbuns();
	this.instance_14.parent = this;
	this.instance_14.setTransform(239.5,54.5);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(14).to({alpha:1},10).wait(287));

	// brussel-sprouts
	this.instance_15 = new lib.holidaymainsbrusselsprouts();
	this.instance_15.parent = this;
	this.instance_15.setTransform(55.5,385);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(19).to({alpha:1},10).wait(282));

	// cranberries
	this.instance_16 = new lib.holidaymainscranberries();
	this.instance_16.parent = this;
	this.instance_16.setTransform(131.5,434);
	this.instance_16.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(24).to({alpha:1},10).wait(277));

	// apples
	this.instance_17 = new lib.holidaymainsapples();
	this.instance_17.parent = this;
	this.instance_17.setTransform(246,449);
	this.instance_17.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(29).to({alpha:1},10).wait(272));

	// potatoes
	this.instance_18 = new lib.holidaymainspotatoes();
	this.instance_18.parent = this;
	this.instance_18.setTransform(250,357);
	this.instance_18.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(34).to({alpha:1},10).wait(267));

	// table
	this.instance_19 = new lib.holidaymainstable();
	this.instance_19.parent = this;
	this.instance_19.setTransform(160,240);

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(311));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(135.1,221.1,395,545);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 320,
	height: 480,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;